/* Regional 17 — eliminación de acreditaciones (solo admin). */
(()=>{'use strict';
const C=window.RV_CONFIG||{};let sb=null,ready=false;
const client=()=>sb||(sb=window.supabase?.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY));
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function toast(msg,error=false){let t=document.getElementById('acr-delete-toast');if(!t){t=document.createElement('div');t.id='acr-delete-toast';t.style.cssText='position:fixed;right:22px;bottom:22px;z-index:100001;padding:12px 16px;border-radius:12px;color:#fff;font:700 12px Inter,system-ui,sans-serif;box-shadow:0 12px 30px #0003;transition:.2s';document.body.appendChild(t)}t.textContent=msg;t.style.background=error?'#a52828':'#087443';t.style.opacity='1';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.opacity='0',2800)}
async function isAdmin(){const s=client();if(!s)return false;const {data:{user}}=await s.auth.getUser();if(!user)return false;const {data:p}=await s.from('profiles').select('role').eq('id',user.id).maybeSingle();return p?.role==='admin'}
async function decorate(id){if(!id||!document.querySelector('.acr2-dialog'))return;if(!ready)ready=await isAdmin();if(!ready)return;const actions=document.querySelector('.acr2-dialog .acr2-actions');if(!actions||actions.querySelector('[data-acr-delete]'))return;const b=document.createElement('button');b.type='button';b.className='acr2-btn';b.dataset.acrDelete='1';b.textContent='🗑️ Eliminar';b.style.cssText='background:#fff1f2!important;color:#b42335!important;border-color:#f1c5ca!important;margin-right:auto!important';b.onclick=async()=>{const name=document.querySelector('.acr2-dialog .acr2-detail div strong')?.textContent||'este acreditado';if(!confirm(`¿Seguro que deseas eliminar la acreditación de ${name}?\n\nEsta acción no se puede deshacer.`))return;b.disabled=true;b.textContent='Eliminando…';const {error}=await client().from('acreditacion_delegados').delete().eq('id',id);if(error){b.disabled=false;b.textContent='🗑️ Eliminar';toast('No se pudo eliminar: '+error.message,true);return}document.querySelector('.acr2-modal')?.remove();toast('Acreditación eliminada correctamente');const nav=document.querySelector('[data-acr-sb]');if(nav)nav.click()};actions.prepend(b)}
document.addEventListener('click',e=>{const v=e.target.closest?.('[data-view]');if(!v)return;const id=v.dataset.view;setTimeout(()=>decorate(id),0)},true);
new MutationObserver(()=>{const m=document.querySelector('.acr2-dialog');if(!m||m.querySelector('[data-acr-delete]'))return;const title=m.querySelector('h2')?.textContent;if(title==='Ficha de acreditación'){const id=document.querySelector('.acr2-table [data-view]')?.dataset.view;if(id)decorate(id)}}).observe(document.body,{childList:true,subtree:true});
})();