// ============================================================
// ACREDITACIÓN — módulo independiente de Evaluaciones
// ============================================================
(function(){
'use strict';
const KEY='regional17_acreditacion';
const DIST=[['17-01','Yamasá'],['17-02','Monte Plata'],['17-03','Bayaguana'],['17-04','Sabana Grande de Boyá'],['17-05','Esperalvillo']];
const AREAS=[['minume','🌎','MINUME'],['centro','🏫','Etapa Centro'],['distrital','🏛️','Etapa Distrital']];
const STATES=['Pendiente','Acreditado','Cancelado'];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const did=id=>{const d=DIST.find(x=>x[0]===id);return d?d[0]+' · '+d[1]:(id||'Sin distrito')};
const aid=()=>`ACR-${new Date().getFullYear()}-${String(Date.now()).slice(-7)}`;
let area='distrital',district='';
const css=`<style id="acreditacion-css"><style>
.acr{max-width:1280px;margin:auto;padding:10px 0 40px}.acr *{box-sizing:border-box}.acr-hero{padding:28px;border-radius:24px;background:linear-gradient(135deg,#071b35,#14527d);color:white;box-shadow:0 15px 40px #0002}.acr-hero h1{margin:7px 0;font-size:30px}.acr-hero p{margin:0;opacity:.78}.acr-areas,.acr-districts,.acr-stats{display:grid;gap:11px;margin:16px 0}.acr-areas{grid-template-columns:repeat(3,1fr)}.acr-districts{grid-template-columns:repeat(5,1fr)}.acr-stats{grid-template-columns:repeat(4,1fr)}.acr-card,.acr-stat,.acr-tool,.acr-wrap{background:var(--card,#fff);border:1px solid #8883;border-radius:17px}.acr-card,.acr-stat{padding:17px}.acr-card{cursor:pointer;text-align:left;color:inherit}.acr-card.active{border-color:#1677b7;box-shadow:0 0 0 2px #1677b722}.acr-card b,.acr-card strong{display:block}.acr-card small,.acr-stat span{opacity:.62}.acr-stat b{font-size:25px;display:block}.acr-tool{padding:12px;display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:14px}.acr-tool input{flex:1;min-width:220px}.acr-btn,.acr-in{min-height:42px;border:1px solid #8884;border-radius:10px;padding:0 13px;background:var(--card,#fff);color:inherit}.acr-btn{cursor:pointer;font-weight:700}.acr-btn.primary{background:#126aa3;color:white;border-color:#126aa3}.acr-wrap{overflow:auto}.acr-table{width:100%;border-collapse:collapse;min-width:950px}.acr-table th,.acr-table td{padding:12px;border-bottom:1px solid #8882;text-align:left;font-size:13px}.acr-table th{font-size:11px;opacity:.6;text-transform:uppercase}.acr-id{font-family:monospace;font-size:11px}.acr-status{padding:6px 9px;border-radius:99px;font-size:11px;font-weight:800}.pending{background:#fff1c9;color:#8a5b00}.ok{background:#dff6e8;color:#18733b}.cancel{background:#ffe0e0;color:#a32828}.acr-empty{text-align:center;padding:50px;opacity:.65}.acr-modal{position:fixed;inset:0;background:#0009;z-index:99999;display:grid;place-items:center;padding:20px}.acr-dialog{width:min(900px,100%);max-height:92vh;overflow:auto;background:var(--card,#fff);color:inherit;border-radius:22px;padding:24px}.acr-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.acr-form label{display:grid;gap:6px;font-size:12px;font-weight:700}.acr-full{grid-column:1/-1}.acr-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.acr-detail{display:grid;grid-template-columns:1fr 1fr;gap:10px}.acr-detail div{padding:12px;background:#8881;border-radius:10px}.acr-detail small{display:block;opacity:.6}@media(max-width:800px){.acr-areas,.acr-districts,.acr-stats{grid-template-columns:1fr 1fr}.acr-form,.acr-detail{grid-template-columns:1fr}.acr-full{grid-column:auto}}@media(max-width:500px){.acr-areas,.acr-districts,.acr-stats{grid-template-columns:1fr}}
</style>`;
function nav(){return document.querySelector('.sidebar nav')||document.querySelector('.sidebar')||document.querySelector('nav')}
function addNav(){const n=nav();if(!n||n.querySelector('[data-acr]'))return;const b=document.createElement('button');b.className='nav-item';b.type='button';b.dataset.acr='1';b.innerHTML='<span>🪪</span><span>Acreditación</span>';b.onclick=open;n.appendChild(b)}
function open(){const root=document.getElementById('content')||document.getElementById('rv-view')||document.getElementById('app');if(!root)return;root.innerHTML=css+`<section class="acr"><div class="acr-hero"><small>REGIONAL 17 · MÓDULO INDEPENDIENTE</small><h1>🪪 Acreditación</h1><p>Registro administrativo de participantes.</p></div><div class="acr-areas">${AREAS.map(a=>`<button class="acr-card ${area===a[0]?'active':''}" data-area="${a[0]}"><span>${a[1]}</span><strong>${a[2]}</strong><small>${a[0]==='distrital'?'Áreas independientes por distrito':'Área independiente'}</small></button>`).join('')}</div><div id="acr-districts"></div><div id="acr-stats" class="acr-stats"></div><div class="acr-tool"><input id="acr-q" class="acr-in" placeholder="🔎 Buscar nombre, ID, teléfono o centro"><select id="acr-state" class="acr-in"><option value="">Todos los estados</option>${STATES.map(s=>`<option>${s}</option>`).join('')}</select><button id="acr-xlsx" class="acr-btn">📊 Excel</button><button id="acr-pdf" class="acr-btn">📄 PDF</button><button id="acr-new" class="acr-btn primary">＋ Registrar acreditado</button></div><div id="acr-list"></div></section>`;root.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{area=b.dataset.area;district='';open()});root.querySelector('#acr-q').oninput=render;root.querySelector('#acr-state').onchange=render;root.querySelector('#acr-new').onclick=()=>form();root.querySelector('#acr-xlsx').onclick=xlsx;root.querySelector('#acr-pdf').onclick=pdf;render()}
function rows(){const q=(document.getElementById('acr-q')?.value||'').toLowerCase(),s=document.getElementById('acr-state')?.value||'';return read().filter(x=>x.area===area&&(!district||x.distrito===district)&&(!s||x.estado===s)&&(!q||[x.id,x.nombre,x.apellido,x.telefono,x.centro,x.distrito].join(' ').toLowerCase().includes(q)))}
function render(){const all=read().filter(x=>x.area===area&&(!district||x.distrito===district)),r=rows(),db=document.getElementById('acr-districts');if(area==='distrital'){db.innerHTML='<div class="acr-districts">'+DIST.map(d=>`<button class="acr-card ${district===d[0]?'active':''}" data-d="${d[0]}"><strong>${d[0]} · ${d[1]}</strong><small>${read().filter(x=>x.area==='distrital'&&x.distrito===d[0]).length} registros</small></button>`).join('')+'</div>';db.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{district=district===b.dataset.d?'':b.dataset.d;render()})}else db.innerHTML='';const p=all.filter(x=>x.estado==='Pendiente').length,a=all.filter(x=>x.estado==='Acreditado').length,c=all.filter(x=>x.estado==='Cancelado').length;document.getElementById('acr-stats').innerHTML=`<div class="acr-stat"><b>${all.length}</b><span>Total</span></div><div class="acr-stat"><b>${a}</b><span>🟢 Acreditados</span></div><div class="acr-stat"><b>${p}</b><span>🟡 Pendientes</span></div><div class="acr-stat"><b>${c}</b><span>🔴 Cancelados</span></div>`;const list=document.getElementById('acr-list');if(!r.length){list.innerHTML='<div class="acr-wrap acr-empty">🪪<br><b>No hay acreditados para esta selección.</b></div>';return}list.innerHTML=`<div class="acr-wrap"><table class="acr-table"><thead><tr><th>ID</th><th>Delegado</th><th>Centro</th><th>Distrito</th><th>Etapa</th><th>Teléfono</th><th>Estado</th><th></th></tr></thead><tbody>${r.map(x=>`<tr><td class="acr-id">${esc(x.id)}</td><td><b>${esc(x.nombre)} ${esc(x.apellido)}</b></td><td>${esc(x.centro)}</td><td>${esc(did(x.distrito))}</td><td>${esc(x.etapa)}</td><td>${esc(x.telefono)}</td><td>${badge(x.estado)}</td><td><button class="acr-btn" data-view="${esc(x.id)}">Ficha</button></td></tr>`).join('')}</tbody></table></div>`;list.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>detail(read().find(x=>x.id===b.dataset.view)))}
function badge(s){return `<span class="acr-status ${s==='Acreditado'?'ok':s==='Cancelado'?'cancel':'pending'}">${s==='Acreditado'?'🟢':s==='Cancelado'?'🔴':'🟡'} ${esc(s)}</span>`}
function form(x={}){const m=document.createElement('div');m.className='acr-modal';m.innerHTML=`<div class="acr-dialog"><h2>${x.id?'Editar acreditación':'Registrar acreditado'}</h2><p style="opacity:.6;font-size:12px">ID automático · Los campos con * son obligatorios.</p><div class="acr-form">${inp('Nombre','nombre',x.nombre,1)}${inp('Apellido','apellido',x.apellido,1)}${inp('Número de teléfono','telefono',x.telefono,1,'tel')}${inp('Cédula (opcional)','cedula',x.cedula)}${inp('Número de acta de nacimiento (opcional)','acta',x.acta)}${sel('Área','area',AREAS.map(a=>[a[0],a[2]]),x.area||area)}${sel('Etapa','etapa',[['MINUME','MINUME'],['Centro','Etapa Centro'],['Distrital','Etapa Distrital']],x.etapa||'Distrital')}${sel('Distrito educativo','distrito',[['','Seleccionar'],...DIST],x.distrito||district)}${inp('Centro educativo','centro',x.centro,1)}${inp('Nombre del familiar / tutor','tutor',x.tutor,1)}${inp('Teléfono del familiar / tutor','tutorTelefono',x.tutorTelefono,1,'tel')}<label class="acr-full"><span>¿Presenta alguna alergia?</span><select id="f-alergia" class="acr-in"><option value="No" ${!x.alergia?'selected':''}>No</option><option value="Sí" ${x.alergia?'selected':''}>Sí</option></select></label>${inp('Tipo de alergia / especificación','alergiaDetalle',x.alergiaDetalle,'',0)}${sel('Estado','estado',STATES.map(s=>[s,s]),x.estado||'Pendiente')}</div><div class="acr-actions"><button class="acr-btn" id="f-cancel">Cancelar</button><button class="acr-btn primary" id="f-save">💾 Guardar</button></div></div>`;document.body.appendChild(m);m.querySelector('#f-cancel').onclick=()=>m.remove();m.querySelector('#f-save').onclick=()=>{const g=k=>m.querySelector('#f-'+k)?.value.trim()||'';const z={id:x.id||aid(),nombre:g('nombre'),apellido:g('apellido'),telefono:g('telefono'),cedula:g('cedula'),acta:g('acta'),area:g('area'),etapa:g('etapa'),distrito:g('distrito'),centro:g('centro'),tutor:g('tutor'),tutorTelefono:g('tutorTelefono'),alergia:g('alergia')==='Sí',alergiaDetalle:g('alergiaDetalle'),estado:g('estado')||'Pendiente',createdAt:x.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!z.nombre||!z.apellido||!z.telefono||!z.centro||!z.tutor||!z.tutorTelefono){alert('Completa los campos obligatorios.');return}const a=read();const dup=a.find(v=>v.id!==z.id&&v.area===z.area&&v.nombre.toLowerCase()===z.nombre.toLowerCase()&&v.apellido.toLowerCase()===z.apellido.toLowerCase()&&v.telefono===z.telefono);if(dup){alert('Ya existe una acreditación con esos datos. ID: '+dup.id);return}const i=a.findIndex(v=>v.id===z.id);i>=0?a[i]=z:a.push(z);save(a);m.remove();render()}}
function inp(l,k,v='',req=0,t='text'){return `<label class="${k==='alergiaDetalle'?'acr-full':''}">${l}${req?' *':''}<input id="f-${k}" class="acr-in" type="${t}" value="${esc(v||'')}" ${req?'required':''}></label>`}function sel(l,k,opts,v=''){return `<label><span>${l}</span><select id="f-${k}" class="acr-in">${opts.map(o=>`<option value="${esc(o[0])}" ${o[0]===v?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`}
function detail(x){const m=document.createElement('div');m.className='acr-modal';const d=(a,b)=>`<div><small>${esc(a)}</small><strong>${esc(b||'—')}</strong></div>`;m.innerHTML=`<div class="acr-dialog"><h2>Ficha de acreditación</h2><p>${esc(x.id)} · ${badge(x.estado)}</p><div class="acr-detail">${d('Nombre completo',x.nombre+' '+x.apellido)}${d('Teléfono',x.telefono)}${d('Cédula',x.cedula)}${d('Acta',x.acta)}${d('Área',AREAS.find(a=>a[0]===x.area)?.[2])}${d('Etapa',x.etapa)}${d('Distrito',did(x.distrito))}${d('Centro educativo',x.centro)}${d('Familiar / tutor',x.tutor)}${d('Teléfono familiar',x.tutorTelefono)}${d('Alergia',x.alergia?'Sí':'No')}${d('Especificación',x.alergiaDetalle)}</div><div class="acr-actions"><button class="acr-btn" id="close">Cerrar</button><button class="acr-btn primary" id="edit">✏️ Editar</button></div></div>`;document.body.appendChild(m);m.querySelector('#close').onclick=()=>m.remove();m.querySelector('#edit').onclick=()=>{m.remove();form(x)}}
function xlsx(){const r=rows();if(!r.length)return alert('No hay registros para exportar.');if(!window.XLSX)return alert('Excel no está disponible.');const data=r.map(x=>({'ID':x.id,'Nombre':x.nombre,'Apellido':x.apellido,'Teléfono':x.telefono,'Cédula':x.cedula||'','Acta de nacimiento':x.acta||'','Área':AREAS.find(a=>a[0]===x.area)?.[2]||x.area,'Etapa':x.etapa,'Distrito':did(x.distrito),'Centro educativo':x.centro,'Familiar/Tutor':x.tutor,'Teléfono familiar':x.tutorTelefono,'Alergia':x.alergia?'Sí':'No','Especificación de alergia':x.alergiaDetalle||'','Estado':x.estado,'Fecha':new Date(x.createdAt).toLocaleString('es-DO')}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Acreditación');XLSX.writeFile(wb,`Acreditacion_${district||area}.xlsx`)}
function pdf(){const r=rows();if(!r.length)return alert('No hay registros para exportar.');const title='Acreditación · '+(AREAS.find(a=>a[0]===area)?.[2]||area)+(district?' · '+did(district):'');const h=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:12px Arial;margin:25px;color:#172033}h1{font-size:20px}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #ccd3db;padding:6px;text-align:left}th{background:#eef3f8}@media print{body{margin:10mm}}</style></head><body><h1>REGIONAL 17 — ${esc(title)}</h1><p>Generado: ${new Date().toLocaleString('es-DO')} · Total: ${r.length}</p><table><thead><tr><th>ID</th><th>Delegado</th><th>Centro</th><th>Distrito</th><th>Etapa</th><th>Teléfono</th><th>Estado</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.nombre)} ${esc(x.apellido)}</td><td>${esc(x.centro)}</td><td>${esc(did(x.distrito))}</td><td>${esc(x.etapa)}</td><td>${esc(x.telefono)}</td><td>${esc(x.estado)}</td></tr>`).join('')}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;const w=window.open('','_blank','width=1200,height=800');if(!w)return alert('Permite ventanas emergentes para generar el PDF.');w.document.write(h);w.document.close()}
window.openAcreditacionDelegados=open;window.renderAcreditacionDelegados=open;function boot(){addNav();new MutationObserver(addNav).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
