/* Regional 17 Volunteers — master admin role management */
(() => {
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const ready=()=>window.supabase&&window.RV_CONFIG?.SUPABASE_URL&&window.RV_CONFIG?.SUPABASE_ANON_KEY;
  let sb=null,isMaster=false,currentUserId=null;
  const toast=(m,err=false)=>{const e=document.createElement('div');e.className='toast'+(err?' error':'');e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)};
  const injectStyles=()=>{if(document.getElementById('rv-admin-polish'))return;const s=document.createElement('style');s.id='rv-admin-polish';s.textContent=`.admin-modal{width:min(1120px,100%);max-height:92vh;box-shadow:0 28px 80px #071b3540}.admin-hero{background:linear-gradient(135deg,#071b35,#174777);color:#fff;border-radius:14px;padding:20px;margin-bottom:15px}.admin-hero-kicker{font-size:9px;letter-spacing:1.5px;text-transform:uppercase;color:#bfd0e3;font-weight:800}.admin-hero h3{font-size:21px;margin:5px 0}.admin-hero p{font-size:10px;color:#d7e3ef;margin:0;line-height:1.5}.admin-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:15px}.admin-summary-card{background:#ffffff12;border:1px solid #ffffff1f;border-radius:10px;padding:10px}.admin-summary-card b{display:block;font-size:18px}.admin-summary-card span{font-size:8px;text-transform:uppercase;color:#c8d8eb}.admin-role-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:15px}.admin-role-card{background:#f8fafc;border:1px solid var(--line);border-radius:12px;padding:12px}.admin-role-card .role-icon{width:30px;height:30px;border-radius:9px;background:#eaf2fa;display:grid;place-items:center;margin-bottom:8px}.admin-role-card strong{font-size:11px;display:block}.admin-role-card span{font-size:9px;color:var(--muted);line-height:1.4;display:block;margin-top:3px}.admin-role-card b{display:block;font-size:17px;color:var(--navy2);margin-top:7px}.admin-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.admin-controls .search{min-width:250px}.admin-filter{height:38px;border:1px solid var(--line);border-radius:9px;background:#fff;padding:0 10px;font-size:11px;color:var(--ink)}.admin-meta{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:5px 0 10px}.admin-meta span{font-size:9px;color:var(--muted)}.admin-table select{height:32px;border:1px solid var(--line);border-radius:7px;background:#fff;padding:0 8px;font-size:10px}.admin-table tr:last-child td{border-bottom:0}.admin-protected{display:inline-flex;align-items:center;gap:5px;background:#fff4dc;color:#93640b;border-radius:999px;padding:4px 8px;font-size:8px;font-weight:800}.admin-modal .person strong{font-size:10px}.admin-modal .person small{font-size:8px}.admin-empty{padding:35px;text-align:center;color:var(--muted);font-size:10px}.admin-close{background:#ffffff18;color:#fff;border:1px solid #ffffff20}.admin-modal .modal-head{display:none}@media(max-width:760px){.admin-summary{grid-template-columns:repeat(2,1fr)}.admin-role-grid{grid-template-columns:1fr}.admin-controls .search{min-width:100%;}.admin-modal{max-height:94vh}.admin-hero{padding:16px}}`;document.head.appendChild(s)};
  async function init(){
    if(!ready())return;
    sb=window.supabase.createClient(window.RV_CONFIG.SUPABASE_URL,window.RV_CONFIG.SUPABASE_ANON_KEY);
    const {data:{session}}=await sb.auth.getSession();if(!session)return;
    currentUserId=session.user.id;
    const r=await sb.rpc('is_master_admin');
    if(!r.error&&r.data===true){isMaster=true;injectStyles();addNav();}
    sb.auth.onAuthStateChange(async(_e,s)=>{currentUserId=s?.user?.id||null;if(!s){isMaster=false;return}const x=await sb.rpc('is_master_admin');isMaster=!x.error&&x.data===true;if(isMaster){injectStyles();addNav()}});
  }
  function addNav(){const nav=document.querySelector('.sidebar nav');if(!isMaster||!nav||nav.querySelector('[data-master-admin]'))return;const b=document.createElement('button');b.className='nav-item';b.dataset.masterAdmin='1';b.innerHTML='<span>⚙</span>Administración';b.onclick=openAdmin;nav.appendChild(b)}
  function observe(){addNav();new MutationObserver(addNav).observe(document.body,{childList:true,subtree:true})}
  async function openAdmin(){
    const [{data:profiles,error:pe},{data:roles,error:re}]=await Promise.all([sb.from('profiles').select('id,email,full_name,role,created_at').order('created_at',{ascending:true}),sb.from('system_roles').select('code,name,description').eq('active',true).order('name')]);
    if(pe)return toast('No se pudieron cargar los usuarios',true);if(re)return toast('No se pudieron cargar los roles',true);
    injectStyles();
    const roleList=roles||[];const roleCounts={};roleList.forEach(r=>roleCounts[r.code]=0);(profiles||[]).forEach(p=>{roleCounts[p.role]=(roleCounts[p.role]||0)+1});
    const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal admin-modal"><div class="modal-body"><div class="admin-hero"><button class="icon-btn admin-close" data-close style="float:right">×</button><div class="admin-hero-kicker">Centro de control</div><h3>Configuración y Administración</h3><p>Gestiona el acceso de la plataforma, revisa los roles y mantiene protegida la cuenta del administrador maestro.</p><div class="admin-summary"><div class="admin-summary-card"><b>${profiles?.length||0}</b><span>Usuarios</span></div><div class="admin-summary-card"><b>${roleList.length}</b><span>Roles activos</span></div><div class="admin-summary-card"><b>${roleCounts.admin||0}</b><span>Administradores</span></div><div class="admin-summary-card"><b>${roleCounts.coordinador||roleCounts.coordinator||0}</b><span>Coordinadores</span></div></div></div><div class="admin-role-grid">${roleList.map((r,i)=>`<div class="admin-role-card"><div class="role-icon">${i===0?'⚙':i===1?'◈':'✓'}</div><strong>${esc(r.name||r.code)}</strong><span>${esc(r.description||'Rol activo en la plataforma')}</span><b>${roleCounts[r.code]||0}</b></div>`).join('')}</div><div class="admin-controls"><div class="search"><span>⌕</span><input id="adminQ" autocomplete="off" placeholder="Buscar usuario por nombre, correo o rol"></div><select id="adminRoleFilter" class="admin-filter"><option value="">Todos los roles</option>${roleList.map(r=>`<option value="${esc(r.code)}">${esc(r.name)}</option>`).join('')}</select><button class="btn small" id="adminRefresh">↻ Actualizar</button></div><div class="admin-meta"><span id="adminResultMeta"></span><span>El administrador maestro está protegido</span></div><div class="table-wrap admin-table"><table style="min-width:820px"><thead><tr><th>Usuario</th><th>Rol actual</th><th>Asignar rol</th><th>Acción</th></tr></thead><tbody id="adminRows"></tbody></table></div></div></div>`;document.body.appendChild(o);
    const rows=o.querySelector('#adminRows'),q=o.querySelector('#adminQ'),filter=o.querySelector('#adminRoleFilter'),meta=o.querySelector('#adminResultMeta');
    const draw=()=>{const text=q.value.toLowerCase().trim(),rf=filter.value;const list=(profiles||[]).filter(p=>(!rf||p.role===rf)&&[p.email,p.full_name,p.role].join(' ').toLowerCase().includes(text));meta.textContent=`Mostrando ${list.length} de ${profiles?.length||0} usuarios`;rows.innerHTML=list.map(p=>{const master=p.id===currentUserId;return `<tr><td><div class="person"><div class="avatar">${esc((p.full_name||p.email||'U')[0].toUpperCase())}</div><div><strong>${esc(p.full_name||'Sin nombre')}</strong><small>${esc(p.email||'')}</small></div></div></td><td><span class="pill ${p.role==='admin'?'success':'neutral'}">${esc(p.role||'voluntario')}</span>${master?'<small style="display:block;color:#9a690d;margin-top:4px">Administrador maestro</small>':''}</td><td><select data-role="${p.id}" ${master?'disabled':''}>${roleList.map(r=>`<option value="${esc(r.code)}" ${p.role===r.code?'selected':''}>${esc(r.name)}</option>`).join('')}</select></td><td>${master?'<span class="admin-protected">🔒 Protegido</span>':`<button class="btn small primary" data-save="${p.id}">Guardar</button>`}</td></tr>`}).join('')||'<tr><td colspan="4"><div class="admin-empty">No encontramos usuarios con esos filtros.</div></td></tr>'};
    draw();q.oninput=draw;filter.onchange=draw;o.querySelector('#adminRefresh').onclick=()=>{q.value='';filter.value='';draw();toast('Vista de administración actualizada')};o.querySelector('[data-close]').onclick=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)o.remove()});
    rows.addEventListener('click',async e=>{const b=e.target.closest('[data-save]');if(!b)return;const id=b.dataset.save;if(id===currentUserId)return toast('El administrador maestro está protegido',true);const select=rows.querySelector(`[data-role="${id}"]`);if(!select)return;b.disabled=true;b.textContent='Guardando…';const r=await sb.rpc('set_user_role',{target_user_id:id,new_role:select.value});if(r.error){toast(r.error.message||'No se pudo asignar el rol',true);b.disabled=false;b.textContent='Guardar';return}const p=profiles.find(x=>x.id===id);if(p)p.role=select.value;toast('Rol actualizado correctamente');draw()});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{init();observe()},{once:true});else{init();observe()}
})();
