/* Regional 17 — announcements module restored from the original communications integration */
(() => {
  'use strict';
  const cfg=window.RV_CONFIG||{};
  let sb=null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const toast=(m,t='success')=>{const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)};
  function client(){if(!sb&&window.supabase&&cfg.SUPABASE_URL)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);return sb}
  async function canPublish(){const s=client();if(!s)return false;const {data:{user}}=await s.auth.getUser();if(!user)return false;const {data:p}=await s.from('profiles').select('role').eq('id',user.id).maybeSingle();return !!p&&['admin','comunicacion'].includes(p.role)}
  async function renderAnnouncements(){const c=document.getElementById('content');if(!c)return;const s=client();if(!s){c.innerHTML='<div class="error-box">Supabase no está disponible.</div>';return}c.innerHTML='<div class="loading"><span class="spinner"></span>Cargando anuncios…</div>';const {data,error}=await s.from('announcements').select('*').order('created_at',{ascending:false});if(error){c.innerHTML=`<div class="error-box">No se pudieron cargar los anuncios: ${esc(error.message)}</div>`;return}const can=await canPublish();c.innerHTML=`<div class="panel communication-panel"><div class="panel-head"><div><h3>📢 Anuncios Regional 17</h3><p>Información oficial para todos los voluntarios.</p></div>${can?'<button class="btn primary" id="newAnnouncement">＋ Nuevo anuncio</button>':''}</div><div id="announcementList">${(data||[]).map(a=>`<article class="announcement-card"><div class="announcement-body"><span class="pill ${esc(a.priority||'normal')}">${a.priority==='urgent'?'Urgente':a.priority==='important'?'Importante':'Normal'}</span><h4>${esc(a.title)}</h4><p>${esc(a.content)}</p><small>${new Date(a.created_at).toLocaleString('es-DO')}</small></div>${can?`<button class="icon-action danger" data-ann-del="${esc(a.id)}">Eliminar</button>`:''}</article>`).join('')||'<div class="empty"><div class="empty-icon">📢</div><h3>No hay anuncios todavía</h3><p>Cuando se publique uno aparecerá aquí.</p></div>'}</div></div>`;document.getElementById('newAnnouncement')?.addEventListener('click',newAnnouncement);document.querySelectorAll('[data-ann-del]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este anuncio?'))return;b.disabled=true;const {error}=await s.from('announcements').delete().eq('id',b.dataset.annDel);if(error){b.disabled=false;return toast(error.message,'error')}toast('Anuncio eliminado');renderAnnouncements()})}
  async function newAnnouncement(){const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><h3>Nuevo anuncio</h3><button class="icon-btn" data-close>×</button></div><div class="modal-body"><form id="announcementForm"><field label="Título del anuncio"><input name="title" required placeholder="Ej.: Reunión general de voluntarios"></field><field label="Contenido"><textarea name="content" required placeholder="Escribe la información que deben conocer los voluntarios…"></textarea></field><field label="Prioridad"><select name="priority"><option value="normal">Normal</option><option value="important">Importante</option><option value="urgent">Urgente</option></select></field><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Publicar anuncio</button></div></form></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());o.querySelector('#announcementForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),{data:{user}}=await client().auth.getUser(),btn=e.submitter;btn.disabled=true;const {error}=await client().from('announcements').insert({title:String(f.get('title')).trim(),content:String(f.get('content')).trim(),priority:f.get('priority'),author_id:user.id});if(error){btn.disabled=false;return toast(error.message,'error')}o.remove();toast('Anuncio publicado');renderAnnouncements()}}
  function styles(){if(document.getElementById('r17-ann-style'))return;const s=document.createElement('style');s.id='r17-ann-style';s.textContent='.communication-panel{max-width:1000px;margin:auto}.announcement-card{display:flex;justify-content:space-between;gap:15px;padding:15px 0;border-bottom:1px solid #edf1f5}.announcement-card h4{font-size:14px;margin:7px 0}.announcement-card p{font-size:11px!important;line-height:1.6}.announcement-card small{font-size:9px;color:#8a96a8}.pill.normal{background:#eef2f6;color:#667085}.pill.important{background:#fff4df;color:#9a690d}.pill.urgent{background:#fdecef;color:#b53343}';document.head.appendChild(s)}
  function install(){const nav=document.querySelector('.sidebar nav');if(!nav||nav.querySelector('[data-r17-announcements]'))return;const b=document.createElement('button');b.type='button';b.className='nav-item';b.dataset.r17Announcements='1';b.innerHTML='<span>📢</span>Anuncios';b.onclick=e=>{e.preventDefault();e.stopPropagation();document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const h=document.querySelector('.topbar h1');if(h)h.textContent='Anuncios';renderAnnouncements()};nav.appendChild(b)}
  function boot(){styles();const obs=new MutationObserver(install);obs.observe(document.body,{childList:true,subtree:true});install()}
  boot();
})();