(() => {
'use strict';
const cfg=window.RV_CONFIG||{};
if(!window.supabase||!cfg.SUPABASE_URL)return;
const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
let me=null,profile=null,districts=[],rows=[],items=[],comments=[],selected=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const role=()=>profile?.role||'voluntario'; const manage=()=>['admin','coordinador'].includes(role());
async function init(){const s=await db.auth.getSession();me=s.data.session?.user;if(!me)return;const p=await db.from('profiles').select('*').eq('id',me.id).maybeSingle();profile=p.data;const d=await db.from('distritos').select('*').order('id');districts=d.data||[];mountNav();subscribe();}
function mountNav(){const nav=document.querySelector('.sidebar nav');if(!nav||nav.querySelector('[data-r17-assignments]'))return;const b=document.createElement('button');b.className='nav-item';b.dataset.r17Assignments='1';b.innerHTML='<span>📋</span>Asignaciones';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open()});nav.appendChild(b)}
function subscribe(){db.channel('r17-assignments').on('postgres_changes',{event:'*',schema:'public',table:'asignaciones'},load).on('postgres_changes',{event:'*',schema:'public',table:'asignacion_items'},load).subscribe()}
async function load(){const r=await db.from('asignaciones').select('*').order('fecha_limite',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});rows=r.data||[];const ids=rows.map(x=>x.id);if(ids.length){const i=await db.from('asignacion_items').select('*').in('asignacion_id',ids).order('orden');items=i.data||[];const c=await db.from('asignacion_comentarios').select('*').in('asignacion_id',ids).order('created_at');comments=c.data||[]}else{items=[];comments=[]}render();}
function progress(a){const x=items.filter(i=>i.asignacion_id===a.id);const done=x.filter(i=>i.completado).length;return {done,total:x.length,p:x.length?Math.round(done/x.length*100):0}}
function status(a){if(a.estado!=='completada'&&a.fecha_limite&&new Date(a.fecha_limite+'T23:59:59')<new Date())return 'atrasada';return a.estado}
function labelStatus(s){return ({pendiente:'Pendiente',en_progreso:'En progreso',completada:'Completada',atrasada:'Atrasada',cancelada:'Cancelada'})[s]||s}
function render(){const c=document.getElementById('content');if(!c)return;c.innerHTML=`<div class="assignments-shell"><div class="assignments-kpis"><div class="assignment-kpi"><strong>${rows.length}</strong><span>Total asignaciones</span></div><div class="assignment-kpi"><strong>${rows.filter(a=>status(a)==='pendiente').length}</strong><span>Pendientes</span></div><div class="assignment-kpi"><strong>${rows.filter(a=>status(a)==='en_progreso').length}</strong><span>En progreso</span></div><div class="assignment-kpi"><strong>${rows.filter(a=>status(a)==='atrasada').length}</strong><span>Atrasadas</span></div></div><div class="assignments-toolbar"><button class="btn" id="aBack">← Dashboard</button>${manage()?'<button class="btn primary" id="aNew">＋ Nueva asignación</button>':''}<select id="aFilter"><option value="all">Todas</option><option value="pendiente">Pendientes</option><option value="en_progreso">En progreso</option><option value="completada">Completadas</option><option value="atrasada">Atrasadas</option></select></div><div class="assignment-list" id="aList"></div></div>`;document.getElementById('aBack').onclick=()=>{document.querySelector('[data-view="dashboard"]')?.click()};document.getElementById('aNew')?.addEventListener('click',form);document.getElementById('aFilter').onchange=renderList;renderList()}
function renderList(){const f=document.getElementById('aFilter')?.value||'all',list=document.getElementById('aList');if(!list)return;const arr=rows.filter(a=>f==='all'||status(a)===f);list.innerHTML=arr.length?arr.map(a=>{const p=progress(a),s=status(a);return `<article class="assignment-card" data-aid="${a.id}"><div class="assignment-head"><div><div class="assignment-title">${esc(a.titulo)}</div><div class="assignment-meta"><span>${esc(a.distrito_id)}</span><span class="assignment-chip ${s==='completada'?'done':s==='en_progreso'?'progress':s==='urgente'?'urgent':''}">${labelStatus(s)}</span><span>Prioridad: ${esc(a.prioridad)}</span>${a.fecha_limite?`<span>Vence: ${esc(a.fecha_limite)}</span>`:''}</div></div><b>${p.p}%</b></div><div class="assignment-progress"><div class="assignment-progress-top"><span>${p.done}/${p.total} puntos completados</span><span>${p.p}%</span></div><div class="assignment-progress-bar"><i style="width:${p.p}%"></i></div></div></article>`}).join(''):'<div class="assignment-empty">No hay asignaciones para este filtro.</div>';list.querySelectorAll('[data-aid]').forEach(x=>x.onclick=()=>detail(x.dataset.aid))}
function form(){const body=`<form class="assignment-form" id="assignmentForm"><div class="assignment-form-grid"><label>Título<input name="titulo" required placeholder="Ej. Preparar capacitación distrital"></label><label>Distrito<select name="distrito_id" required>${districts.map(d=>`<option value="${esc(d.id)}">${esc(d.id)} · ${esc(d.nombre)}</option>`).join('')}</select></label><label>Prioridad<select name="prioridad"><option value="baja">Baja</option><option value="media" selected>Media</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></label><label>Fecha límite<input name="fecha_limite" type="date"></label></div><label>Descripción<textarea name="descripcion" placeholder="Describe claramente lo que debe realizar el distrito"></textarea></label><div><b>Checklist</b><div class="assignment-items-editor" id="itemEditor"><div class="assignment-item-row"><input name="item" placeholder="Primer punto de la tarea"><button type="button" class="btn" id="addItem">＋</button></div></div></div><div class="assignment-actions"><button type="button" class="btn" id="cancelForm">Cancelar</button><button class="btn primary">Crear asignación</button></div></form>`;const o=window.modal?window.modal('Nueva asignación',body):simpleModal('Nueva asignación',body);o.querySelector('#cancelForm').onclick=()=>o.remove();o.querySelector('#addItem').onclick=()=>{const d=document.createElement('div');d.className='assignment-item-row';d.innerHTML='<input name="item" placeholder="Otro punto del checklist"><button type="button" class="btn">×</button>';d.querySelector('button').onclick=()=>d.remove();o.querySelector('#itemEditor').appendChild(d)};o.querySelector('#assignmentForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),payload={titulo:String(fd.get('titulo')).trim(),descripcion:String(fd.get('descripcion')).trim()||null,distrito_id:fd.get('distrito_id'),prioridad:fd.get('prioridad'),fecha_limite:fd.get('fecha_limite')||null,created_by:me.id};const r=await db.from('asignaciones').insert(payload).select().single();if(r.error)return alert(r.error.message);const vals=[...e.target.querySelectorAll('input[name="item"]')].map(x=>x.value.trim()).filter(Boolean);if(vals.length)await db.from('asignacion_items').insert(vals.map((titulo,orden)=>({asignacion_id:r.data.id,titulo,orden})));o.remove();await load()}}
function simpleModal(title,body){const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><h3>${esc(title)}</h3><button data-x>×</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(o);o.querySelector('[data-x]').onclick=()=>o.remove();return o}
async function detail(id){selected=id;const a=rows.find(x=>x.id===id);if(!a)return;const p=progress(a),its=items.filter(i=>i.asignacion_id===id),cs=comments.filter(c=>c.asignacion_id===id),s=status(a);const body=`<div class="assignment-detail"><div class="assignment-panel"><h2>${esc(a.titulo)}</h2><p>${esc(a.descripcion||'Sin descripción')}</p><div class="assignment-meta"><span>${esc(a.distrito_id)}</span><span>${labelStatus(s)}</span><span>Prioridad ${esc(a.prioridad)}</span>${a.fecha_limite?`<span>Vence ${esc(a.fecha_limite)}</span>`:''}</div><div class="assignment-progress"><div class="assignment-progress-top"><span>Progreso</span><b>${p.p}%</b></div><div class="assignment-progress-bar"><i style="width:${p.p}%"></i></div></div><div class="assignment-checklist">${its.length?its.map(i=>`<label class="assignment-check ${i.completado?'done':''}"><input type="checkbox" data-item="${i.id}" ${i.completado?'checked':''}><span>${esc(i.titulo)}</span></label>`).join(''):'<div class="assignment-empty">Esta asignación no tiene checklist.</div>'}</div></div><aside class="assignment-panel"><b>Comentarios</b><div class="assignment-comments">${cs.map(c=>`<div class="assignment-comment"><small>${esc(c.user_id===me.id?'Tú':'Usuario')} · ${new Date(c.created_at).toLocaleString('es-DO')}</small>${esc(c.comentario)}</div>`).join('')||'<small>Sin comentarios todavía.</small>'}</div><form id="commentForm" class="assignment-form" style="margin-top:12px"><textarea name="comentario" placeholder="Agregar comentario..."></textarea><button class="btn primary">Comentar</button></form>${manage()?`<div class="assignment-actions"><button class="btn" id="markDone">Marcar completada</button>${role()==='admin'?'<button class="btn" id="deleteA">Eliminar</button>':''}</div>`:''}</aside></div>`;const o=simpleModal('Detalle de asignación',body);o.querySelectorAll('[data-item]').forEach(ch=>ch.onchange=async()=>{const r=await db.from('asignacion_items').update({completado:ch.checked}).eq('id',ch.dataset.item);if(r.error)alert(r.error.message);await syncState(id);detail(id)});o.querySelector('#commentForm').onsubmit=async e=>{e.preventDefault();const text=String(new FormData(e.target).get('comentario')).trim();if(!text)return;const r=await db.from('asignacion_comentarios').insert({asignacion_id:id,user_id:me.id,comentario:text});if(r.error)alert(r.error.message);else{await load();detail(id)}};o.querySelector('#markDone')?.addEventListener('click',async()=>{await db.from('asignaciones').update({estado:'completada'}).eq('id',id);o.remove();await load()});o.querySelector('#deleteA')?.addEventListener('click',async()=>{if(confirm('¿Eliminar esta asignación?')){await db.from('asignaciones').delete().eq('id',id);o.remove();await load()}})}
async function syncState(id){const its=items.filter(i=>i.asignacion_id===id);const done=its.filter(i=>i.completado).length;const estado=its.length&&done===its.length?'completada':done?'en_progreso':'pendiente';await db.from('asignaciones').update({estado}).eq('id',id);await load()}
function open(){load().then(()=>{const b=document.querySelector('.nav-item[data-r17-assignments]');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b?.classList.add('active')})}
window.addEventListener('load',()=>{init();new MutationObserver(()=>mountNav()).observe(document.body,{childList:true,subtree:true})});
})();