/* Regional 17 Volunteers — communications & volunteer account module */
(() => {
  'use strict';
  const cfg=window.RV_CONFIG||{};
  let sb=null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const toast=(m,t='success')=>{const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)};
  function ready(){return cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase}
  async function client(){if(!sb&&ready())sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);return sb}
  function authCard(){return `<div class="auth-extra"><button class="btn" id="registerVolunteer">Crear cuenta de voluntario</button></div>`}
  async function register(){const s=await client();if(!s)return toast('Supabase no está configurado','error');const {data,error}=await s.rpc('available_volunteers');if(error)return toast(error.message,'error');const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><div><h3>Crear cuenta de voluntario</h3><p style="margin:4px 0;color:#667085;font-size:12px">Selecciona tu registro existente en Regional 17.</p></div><button class="icon-btn" data-close>×</button></div><div class="modal-body"><form id="registerForm"><field label="Nombre del voluntario"><select name="volunteer_id" required><option value="">Selecciona tu nombre</option>${(data||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.nombre)}</option>`).join('')}</select></field><field label="Correo electrónico"><input type="email" name="email" required placeholder="tu@correo.com"></field><field label="Contraseña"><input type="password" name="password" minlength="8" required placeholder="Mínimo 8 caracteres"></field><field label="Confirmar contraseña"><input type="password" name="confirm" minlength="8" required></field><p class="form-help">La cuenta quedará vinculada al voluntario seleccionado y recibirá automáticamente el rol Voluntario.</p><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Crear cuenta</button></div></form></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());o.querySelector('#registerForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),email=String(fd.get('email')).trim(),pw=String(fd.get('password')),confirm=String(fd.get('confirm'));if(pw!==confirm)return toast('Las contraseñas no coinciden','error');const {data:sign,error:se}=await s.auth.signUp({email,password:pw});if(se) return toast(se.message,'error');if(sign.user){const {error:ce}=await s.rpc('claim_volunteer_account',{target_volunteer_id:fd.get('volunteer_id')});if(ce){await s.auth.signOut();return toast(ce.message,'error')}}o.remove();toast('Cuenta creada correctamente.');};}
  function communicationView(type){return type==='chat'?chatView():announcementView()}
  async function announcementView(){const s=await client();const {data,error}=await s.from('announcements').select('*').order('created_at',{ascending:false});if(error)return `<div class="error-box">${esc(error.message)}</div>`;return `<div class="panel communication-panel"><div class="panel-head"><div><h3>📢 Anuncios</h3><p>Información oficial para los voluntarios.</p></div><button class="btn primary" id="newAnnouncement">＋ Nuevo anuncio</button></div><div id="announcementList">${(data||[]).map(a=>`<article class="announcement ${esc(a.priority)}"><div><span class="pill">${esc(a.priority)}</span><h4>${esc(a.title)}</h4><p>${esc(a.content)}</p><small>${new Date(a.created_at).toLocaleString('es-DO')}</small></div><div class="actions"><button class="icon-action danger" data-ann-del="${a.id}">Eliminar</button></div></article>`).join('')||'<p>No hay anuncios publicados.</p>'}</div></div>`}
  function chatView(){return `<div class="panel chat-panel"><div class="panel-head"><div><h3>💬 Chat Regional 17</h3><p>Comunicación general entre usuarios.</p></div></div><div id="chatMessages" class="chat-messages"><div class="loading">Cargando mensajes…</div></div><form id="chatForm" class="chat-form"><input id="chatInput" maxlength="2000" placeholder="Escribe un mensaje…" autocomplete="off"><button class="btn primary">Enviar</button></form></div>`}
  async function loadChat(){const s=await client(),box=document.getElementById('chatMessages');if(!s||!box)return;const {data,error}=await s.from('chat_messages').select('id,user_id,message,created_at,profiles(full_name)').order('created_at',{ascending:true}).limit(200);if(error){box.innerHTML=`<p>${esc(error.message)}</p>`;return}box.innerHTML=(data||[]).map(m=>`<div class="chat-message"><div class="avatar">${esc((m.profiles?.full_name||'U')[0])}</div><div><strong>${esc(m.profiles?.full_name||'Usuario')}</strong><p>${esc(m.message)}</p><small>${new Date(m.created_at).toLocaleString('es-DO')}</small></div></div>`).join('')||'<p>No hay mensajes todavía.</p>';box.scrollTop=box.scrollHeight}
  async function bindChat(){const s=await client();await loadChat();document.getElementById('chatForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=document.getElementById('chatInput'),msg=input.value.trim();if(!msg)return;const {data:{user}}=await s.auth.getUser();if(!user)return toast('Debes iniciar sesión','error');const {error}=await s.from('chat_messages').insert({user_id:user.id,message:msg});if(error)return toast(error.message,'error');input.value='';await loadChat()});if(s){s.channel('regional17-chat').on('postgres_changes',{event:'*',schema:'public',table:'chat_messages'},loadChat).subscribe()}}
  function bindAnnouncements(){document.getElementById('newAnnouncement')?.addEventListener('click',async()=>{const s=await client();const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><h3>Nuevo anuncio</h3><button class="icon-btn" data-close>×</button></div><div class="modal-body"><form id="announcementForm"><field label="Título del anuncio"><input name="title" required placeholder="Ej.: Reunión general de voluntarios"></field><field label="Contenido"><textarea name="content" required placeholder="Escribe aquí la información que deben conocer los voluntarios…"></textarea></field><field label="Prioridad"><select name="priority"><option value="normal">Normal</option><option value="important">Importante</option><option value="urgent">Urgente</option></select></field><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Publicar anuncio</button></div></form></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());o.querySelector('#announcementForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),{data:{user}}=await s.auth.getUser(),{error}=await s.from('announcements').insert({title:String(fd.get('title')).trim(),content:String(fd.get('content')).trim(),priority:fd.get('priority'),author_id:user?.id});if(error)return toast(error.message,'error');o.remove();toast('Anuncio publicado');location.reload()}});document.querySelectorAll('[data-ann-del]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este anuncio?'))return;const {error}=await (await client()).from('announcements').delete().eq('id',b.dataset.annDel);if(error)return toast(error.message,'error');toast('Anuncio eliminado');location.reload()})}
  window.R17Communications={register,communicationView,bindChat,bindAnnouncements,authCard};
  document.addEventListener('click',e=>{if(e.target.id==='registerVolunteer')register()});
})();