(() => {
  'use strict';
  const STYLE_ID='rv-digital-map-style';
  const addStyle=()=>{if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
  .map.digital-map-shell{position:relative;background:#031421;box-shadow:0 18px 55px #02101d66;border:1px solid #0b4561}
  .digital-map-shell .leaflet-tile-pane{filter:brightness(.42) saturate(.7) contrast(1.15) hue-rotate(150deg)}
  .digital-map-shell .leaflet-control-zoom a{background:#062538cc;color:#8beaff;border-color:#12617d}
  .digital-map-shell .leaflet-control-attribution{background:#031421cc!important;color:#5fa8bd!important}
  .digital-map-shell .leaflet-control-attribution a{color:#6ed9ef!important}
  .rv-network-canvas{position:absolute;inset:0;width:100%;height:100%;z-index:350;pointer-events:none;mix-blend-mode:screen}
  .rv-map-grid{position:absolute;inset:0;z-index:351;pointer-events:none;background-image:linear-gradient(#19b9dc0b 1px,transparent 1px),linear-gradient(90deg,#19b9dc0b 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(to bottom,#000,transparent 92%)}
  .rv-map-scan{position:absolute;inset:0;z-index:352;pointer-events:none;background:linear-gradient(180deg,transparent 0%,#16d8ff0d 48%,transparent 52%);animation:rv-scan 6s linear infinite}
  .rv-map-hud{position:absolute;z-index:500;left:14px;bottom:14px;padding:9px 11px;border:1px solid #1c7188;background:#031b2acc;backdrop-filter:blur(8px);border-radius:10px;color:#8ce8fa;font-size:9px;letter-spacing:.5px;box-shadow:0 8px 25px #00111d66}
  .rv-map-hud b{color:#d8fbff}.rv-digital-marker{width:18px;height:18px;border-radius:50%;background:#20dfff;border:2px solid #d8fbff;box-shadow:0 0 0 5px #20dfff18,0 0 18px #20dfff;position:relative}.rv-digital-marker:after{content:'';position:absolute;inset:-9px;border:1px solid #20dfff55;border-radius:50%;animation:rv-pulse 2s ease-out infinite}
  .rv-digital-event{background:#f3b343;box-shadow:0 0 0 5px #f3b34318,0 0 18px #f3b343;border-color:#fff5d4}.rv-digital-event:after{border-color:#f3b34355}
  @keyframes rv-pulse{0%{transform:scale(.5);opacity:.9}100%{transform:scale(1.45);opacity:0}}@keyframes rv-scan{0%{transform:translateY(-100%)}100%{transform:translateY(100%)}}
  `;document.head.appendChild(s)};
  function drawNetwork(canvas){const ctx=canvas.getContext('2d');let w=0,h=0,nodes=[];const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);nodes=[];const count=Math.max(32,Math.min(85,Math.floor(w*h/12000)));for(let i=0;i<count;i++)nodes.push({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.045,vy:(Math.random()-.5)*.045,r:Math.random()*1.7+.5})};resize();let raf;const frame=()=>{ctx.clearRect(0,0,w,h);for(const a of nodes){a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1}for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=i+1;j<nodes.length;j++){const b=nodes[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d<115){ctx.strokeStyle=`rgba(20,210,246,${(1-d/115)*.18})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}}for(const p of nodes){ctx.fillStyle='rgba(42,225,255,.78)';ctx.shadowBlur=10;ctx.shadowColor='#14d9ff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}raf=requestAnimationFrame(frame)};frame();return()=>cancelAnimationFrame(raf)}
  function enhance(){const map=document.querySelector('#map');if(!map||map.dataset.digitalMap)return;map.dataset.digitalMap='1';addStyle();map.classList.add('digital-map-shell');const canvas=document.createElement('canvas');canvas.className='rv-network-canvas';map.appendChild(canvas);const grid=document.createElement('div');grid.className='rv-map-grid';map.appendChild(grid);const scan=document.createElement('div');scan.className='rv-map-scan';map.appendChild(scan);const hud=document.createElement('div');hud.className='rv-map-hud';hud.innerHTML='<b>R17 DIGITAL NETWORK</b> · NODOS ACTIVOS · MONTE PLATA';map.appendChild(hud);const stop=drawNetwork(canvas);map._rvDigitalStop=stop;setTimeout(()=>{map.querySelectorAll('.leaflet-marker-icon').forEach(el=>{if(el.classList.contains('event-marker')){el.classList.add('rv-digital-event')}})},120);new MutationObserver(()=>map.querySelectorAll('.leaflet-marker-icon').forEach(el=>{if(el.classList.contains('event-marker'))el.classList.add('rv-digital-event')})).observe(map,{subtree:true,childList:true})}
  new MutationObserver(enhance).observe(document.documentElement,{subtree:true,childList:true});setTimeout(enhance,250);
})();
