(() => {
  'use strict';
  const STYLE_ID='rv-digital-map-style';
  const addStyle=()=>{if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
  .map.digital-map-shell{position:relative;overflow:hidden;background:#020f1b;border:1px solid #0d536c;box-shadow:0 18px 55px rgba(0,20,35,.45),inset 0 0 80px rgba(0,204,255,.035)}
  .digital-map-shell .leaflet-tile-pane{filter:brightness(.38) saturate(.72) contrast(1.18) hue-rotate(145deg)}
  .digital-map-shell .leaflet-control-zoom a{background:rgba(3,28,45,.94);color:#8beaff;border-color:#12617d}
  .digital-map-shell .leaflet-control-attribution{background:rgba(2,15,27,.88)!important;color:#5fa8bd!important}.digital-map-shell .leaflet-control-attribution a{color:#6ed9ef!important}
  .digital-map-shell .leaflet-popup-content-wrapper,.digital-map-shell .leaflet-popup-tip{background:rgba(3,25,40,.96);color:#d9f8ff;border:1px solid #12617d}.digital-map-shell .leaflet-popup-content{margin:12px 14px}.digital-map-shell .leaflet-popup-close-button{color:#8beaff!important}
  .rv-network-canvas,.rv-map-grid,.rv-map-scan,.rv-map-vignette,.rv-map-hud,.rv-map-legend{position:absolute;pointer-events:none}.rv-network-canvas{inset:0;width:100%;height:100%;z-index:450;mix-blend-mode:screen}
  .rv-map-grid{inset:0;z-index:451;background-image:linear-gradient(rgba(25,185,220,.075) 1px,transparent 1px),linear-gradient(90deg,rgba(25,185,220,.075) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(to bottom,#000 0%,rgba(0,0,0,.85) 60%,transparent 100%)}
  .rv-map-scan{inset:-30% 0;z-index:452;background:linear-gradient(180deg,transparent 0%,rgba(22,216,255,.015) 45%,rgba(22,216,255,.12) 50%,rgba(22,216,255,.015) 55%,transparent 100%);animation:rv-map-scan 7s linear infinite}.rv-map-vignette{inset:0;z-index:453;background:radial-gradient(circle at 50% 45%,transparent 42%,rgba(0,8,16,.22) 78%,rgba(0,6,12,.68) 100%)}
  .rv-map-hud{z-index:700;left:14px;top:14px;padding:9px 12px;border:1px solid #1c7188;background:rgba(3,27,44,.82);backdrop-filter:blur(9px);border-radius:10px;color:#8ce8fa;font:700 9px/1.4 Inter,system-ui,sans-serif;letter-spacing:.7px;box-shadow:0 8px 25px rgba(0,17,29,.4)}.rv-map-hud b{color:#d8fbff}.rv-map-hud span{display:block;color:#5fa8bd;font-size:8px;font-weight:600;letter-spacing:.45px;margin-top:2px}
  .rv-map-legend{z-index:700;right:14px;bottom:14px;display:flex;gap:10px;align-items:center;padding:8px 10px;border:1px solid #15566c;background:rgba(3,27,44,.78);backdrop-filter:blur(8px);border-radius:9px;color:#8bc8d8;font:600 8px/1 Inter,system-ui,sans-serif}.rv-map-legend i{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:4px}.rv-map-legend .center-dot{background:#20dfff;box-shadow:0 0 9px #20dfff}.rv-map-legend .event-dot{background:#f3b343;box-shadow:0 0 9px #f3b343}
  .digital-map-shell .leaflet-marker-icon{filter:drop-shadow(0 0 7px rgba(32,223,255,.8))}.digital-map-shell .event-marker{background:#f3b343;color:#1b1405;border:2px solid #fff5d4;box-shadow:0 0 0 5px rgba(243,179,67,.12),0 0 18px rgba(243,179,67,.9)}
  .digital-map-shell .rv-digital-marker{width:18px!important;height:18px!important;border-radius:50%;background:#20dfff;border:2px solid #d8fbff;box-shadow:0 0 0 5px rgba(32,223,255,.12),0 0 18px rgba(32,223,255,.95);position:relative}.digital-map-shell .rv-digital-marker::after{content:'';position:absolute;inset:-9px;border:1px solid rgba(32,223,255,.45);border-radius:50%;animation:rv-pulse 2s ease-out infinite}.digital-map-shell .rv-digital-event{background:#f3b343!important;box-shadow:0 0 0 5px rgba(243,179,67,.14),0 0 18px rgba(243,179,67,.95)!important}
  @keyframes rv-pulse{0%{transform:scale(.5);opacity:.9}100%{transform:scale(1.45);opacity:0}}@keyframes rv-map-scan{0%{transform:translateY(-35%)}100%{transform:translateY(135%)}}
  @media(max-width:760px){.rv-map-hud{left:8px;top:8px;padding:7px 9px;font-size:8px}.rv-map-hud span{font-size:7px}.rv-map-legend{right:8px;bottom:8px;padding:6px 8px;gap:7px;font-size:7px}.rv-map-grid{background-size:30px 30px}}
  `;document.head.appendChild(s)};
  function markerPoints(mapEl){const bounds=mapEl.getBoundingClientRect();return [...mapEl.querySelectorAll('.leaflet-marker-icon')].map(el=>{const r=el.getBoundingClientRect();return{x:r.left-bounds.left+r.width/2,y:r.top-bounds.top+r.height/2,event:el.classList.contains('event-marker')||el.classList.contains('rv-digital-event')}}).filter(p=>p.x>=-30&&p.y>=-30&&p.x<=bounds.width+30&&p.y<=bounds.height+30)}
  function drawNetwork(canvas,mapEl){const ctx=canvas.getContext('2d');let width=1,height=1,raf=0,ambient=[];function resize(){const rect=mapEl.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=Math.max(1,rect.width);height=Math.max(1,rect.height);canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.max(24,Math.min(72,Math.floor(width*height/16000)));ambient=Array.from({length:count},()=>({x:Math.random()*width,y:Math.random()*height,vx:(Math.random()-.5)*.035,vy:(Math.random()-.5)*.035,r:Math.random()*1.4+.45}))}resize();const ro=new ResizeObserver(resize);ro.observe(mapEl);function frame(){ctx.clearRect(0,0,width,height);for(const p of ambient){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>width)p.vx*=-1;if(p.y<0||p.y>height)p.vy*=-1}const points=markerPoints(mapEl),nodes=points.length?points:ambient;for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j],distance=Math.hypot(a.x-b.x,a.y-b.y);if(distance<210){ctx.strokeStyle=`rgba(20,210,246,${Math.max(.025,(1-distance/210)*.25)})`;ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}for(const a of ambient){let nearest=null,nearestDistance=135;for(const p of points){const d=Math.hypot(a.x-p.x,a.y-p.y);if(d<nearestDistance){nearest=p;nearestDistance=d}}if(nearest){ctx.strokeStyle=`rgba(20,210,246,${(1-nearestDistance/135)*.11})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(nearest.x,nearest.y);ctx.stroke()}ctx.fillStyle='rgba(42,225,255,.62)';ctx.shadowBlur=8;ctx.shadowColor='#14d9ff';ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const p of nodes){ctx.fillStyle=p.event?'#f3b343':'#20dfff';ctx.shadowBlur=11;ctx.shadowColor=p.event?'#f3b343':'#14d9ff';ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}raf=requestAnimationFrame(frame)}frame();return()=>{cancelAnimationFrame(raf);ro.disconnect()}}
  function decorateMarkers(mapEl){mapEl.querySelectorAll('.leaflet-marker-icon').forEach(el=>{if(el.classList.contains('event-marker'))el.classList.add('rv-digital-event');else if(!el.classList.contains('rv-digital-marker'))el.classList.add('rv-digital-marker')})}
  function enhance(){const mapEl=document.querySelector('#map');if(!mapEl||mapEl.dataset.digitalMap==='1')return;mapEl.dataset.digitalMap='1';addStyle();mapEl.classList.add('digital-map-shell');const canvas=document.createElement('canvas');canvas.className='rv-network-canvas';mapEl.appendChild(canvas);const grid=document.createElement('div');grid.className='rv-map-grid';mapEl.appendChild(grid);const scan=document.createElement('div');scan.className='rv-map-scan';mapEl.appendChild(scan);const vignette=document.createElement('div');vignette.className='rv-map-vignette';mapEl.appendChild(vignette);const hud=document.createElement('div');hud.className='rv-map-hud';hud.innerHTML='<b>R17 DIGITAL NETWORK</b><span>RED REGIONAL · NODOS EN TIEMPO REAL</span>';mapEl.appendChild(hud);const legend=document.createElement('div');legend.className='rv-map-legend';legend.innerHTML='<span><i class="center-dot"></i>Centro</span><span><i class="event-dot"></i>Evento</span>';mapEl.appendChild(legend);decorateMarkers(mapEl);mapEl._rvDigitalStop=drawNetwork(canvas,mapEl);const observer=new MutationObserver(()=>decorateMarkers(mapEl));observer.observe(mapEl,{subtree:true,childList:true});mapEl._rvDigitalObserver=observer}
  new MutationObserver(enhance).observe(document.documentElement,{subtree:true,childList:true});setTimeout(enhance,250);
})();
