/* Regional 17 · Importación masiva para Evaluaciones y Acreditación. */
(()=>{'use strict';
const C=window.RV_CONFIG||{}; const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let target='evaluacion', currentEval=null, currentCommission=null, parsed=[];
const countries={DO:['República Dominicana','DO'],US:['Estados Unidos','US'],CN:['China','CN'],FR:['Francia','FR'],RU:['Rusia','RU'],GB:['Reino Unido','GB'],MX:['México','MX'],BR:['Brasil','BR'],CO:['Colombia','CO'],ES:['España','ES'],DE:['Alemania','DE'],AR:['Argentina','AR'],CL:['Chile','CL'],PE:['Perú','PE'],IT:['Italia','IT'],JP:['Japón','JP'],KR:['Corea del Sur','KR'],CA:['Canadá','CA'],VE:['Venezuela','VE'],EC:['Ecuador','EC'],PA:['Panamá','PA'],CR:['Costa Rica','CR'],GT:['Guatemala','GT'],HN:['Honduras','HN'],NI:['Nicaragua','NI'],SV:['El Salvador','SV'],HT:['Haití','HT'],BO:['Bolivia','BO'],UY:['Uruguay','UY'],PY:['Paraguay','PY'],PT:['Portugal','PT'],NL:['Países Bajos','NL'],SE:['Suecia','SE'],NO:['Noruega','NO'],CH:['Suiza','CH'],ZA:['Sudáfrica','ZA'],EG:['Egipto','EG'],NG:['Nigeria','NG'],AU:['Australia','AU']};
const flag=code=>{code=String(code||'').toUpperCase();return /^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(c=>127397+c.charCodeAt(0))):'🌐'};
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const findKey=(obj,keys)=>{for(const k of Object.keys(obj||{})){const n=norm(k).replace(/[^a-z0-9]/g,'');if(keys.some(x=>n===x||n.includes(x)))return obj[k]}return ''};
function styles(){if(document.getElementById('r17-import-css'))return;const s=document.createElement('style');s.id='r17-import-css';s.textContent=`#r17ImportBtn{margin-left:8px}#r17ImportModal{position:fixed;inset:0;z-index:10080;background:rgba(3,12,25,.68);display:grid;place-items:center;padding:16px}#r17ImportModal .im-card{width:min(1000px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 30px 100px #0007}#r17ImportModal .im-head{padding:18px 20px;background:linear-gradient(135deg,#071b35,#174777);color:#fff;display:flex;justify-content:space-between;align-items:center;gap:10px}#r17ImportModal h3{margin:0;font-size:18px}#r17ImportModal .im-body{padding:18px}.im-drop{border:2px dashed #b9cadb;border-radius:14px;padding:25px;text-align:center;background:#f7fafc;cursor:pointer}.im-drop strong{display:block;margin-bottom:5px}.im-drop span{font-size:10px;color:#64778c}.im-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.im-tools button,.im-actions button{border:1px solid #d4dfeb;background:#fff;border-radius:9px;padding:9px 12px;font-weight:800;font-size:11px;cursor:pointer}.im-primary{background:#0b74c9!important;color:#fff;border-color:#0b74c9!important}.im-table{width:100%;border-collapse:collapse;font-size:10px}.im-table th,.im-table td{padding:7px;border-bottom:1px solid #e5ebf1;text-align:left}.im-table th{background:#f2f6fa;position:sticky;top:0}.im-status{padding:10px;border-radius:9px;background:#eef6ff;color:#315f91;font-size:10px;margin-bottom:10px}.im-actions{display:flex;justify-content:flex-end;gap:8px;padding:0 18px 18px;flex-wrap:wrap}.im-x{border:0;background:#ffffff18;color:#fff;border-radius:8px;width:34px;height:34px;font-size:20px}.im-map{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.im-map label{font-size:9px;font-weight:800;color:#53677d}.im-map select{width:100%;padding:8px;border:1px solid #d5e0ea;border-radius:8px;font-size:10px}@media(max-width:700px){.im-map{grid-template-columns:1fr}.im-table{min-width:700px}.im-table-wrap{overflow:auto}}`;document.head.appendChild(s)}
function close(){document.getElementById('r17ImportModal')?.remove()}
function open(type){target=type;styles();close();parsed=[];currentEval=null;currentCommission=null;const m=document.createElement('div');m.id='r17ImportModal';m.innerHTML=`<div class="im-card"><div class="im-head"><div><div style="font-size:9px;letter-spacing:1.4px;font-weight:800;color:#bcd0e6">REGIONAL 17 · CARGA MASIVA</div><h3>Importar ${type==='evaluacion'?'delegados y participantes':'acreditados'}</h3></div><button class="im-x">×</button></div><div class="im-body"><div class="im-status" id="imStatus">Puedes cargar Excel (.xlsx/.xls), CSV o PDF. El sistema intentará reconocer automáticamente nombres, países, comisiones, distrito y datos de acreditación.</div><label class="im-drop" for="imFile"><strong>📁 Seleccionar archivo</strong><span>Excel, CSV o PDF · también puedes arrastrarlo aquí</span><input id="imFile" type="file" accept=".xlsx,.xls,.csv,.pdf" hidden></label><div id="imOptions"></div><div id="imPreview"></div></div><div class="im-actions"><button class="im-cancel">Cancelar</button><button class="im-primary" id="imImport" disabled>Importar datos</button></div></div>`;document.body.appendChild(m);m.querySelector('.im-x').onclick=close;m.querySelector('.im-cancel').onclick=close;m.querySelector('#imFile').onchange=e=>parseFile(e.target.files[0]);}
async function parseFile(file){if(!file)return;const status=document.querySelector('#imStatus');status.textContent='Leyendo archivo…';try{if(/\.pdf$/i.test(file.name)){await loadPdf();parsed=await parsePdf(file)}else if(/\.csv$/i.test(file.name)){parsed=parseCsv(await file.text())}else{if(!window.XLSX)throw new Error('No se pudo cargar el lector de Excel.');const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];parsed=XLSX.utils.sheet_to_json(ws,{defval:''})}renderPreview(file.name)}catch(e){status.textContent='No se pudo leer el archivo: '+e.message}}
function parseCsv(t){const lines=t.split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const split=l=>l.split(sep).map(x=>x.replace(/^\s*"|"\s*$/g,'').trim());const h=split(lines[0]);return lines.slice(1).map(l=>{const a=split(l),o={};h.forEach((k,i)=>o[k]=a[i]??'');return o})}
async function loadPdf(){if(window.pdfjsLib)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs';s.type='module';s.onload=()=>setTimeout(()=>window.pdfjsLib?resolve():reject(new Error('PDF.js no disponible')),100);s.onerror=()=>reject(new Error('No se pudo cargar el lector PDF'));document.head.appendChild(s)})}
async function parsePdf(file){if(!window.pdfjsLib)throw new Error('Lector PDF no disponible');const buf=await file.arrayBuffer();const pdf=await window.pdfjsLib.getDocument({data:buf}).promise;const rows=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const tc=await page.getTextContent();const lines={};for(const it of tc.items){const y=Math.round(it.transform[5]);(lines[y]||(lines[y]=[])).push(it.str)}Object.keys(lines).sort((a,b)=>b-a).forEach(y=>{const text=lines[y].join(' ').replace(/\s+/g,' ').trim();if(text)rows.push({'Datos':text})})}return rows}
function renderPreview(file){const box=document.querySelector('#imPreview'),status=document.querySelector('#imStatus');if(!parsed.length){status.textContent='El archivo no contiene filas reconocibles.';return}status.textContent=`${file}: ${parsed.length} filas detectadas. Revisa la vista previa antes de importar.`;const first=parsed.slice(0,12),headers=[...new Set(first.flatMap(r=>Object.keys(r)))].slice(0,8);box.innerHTML=`<div class="im-map"><label>Nombre<select id="mapName"><option value="">Automático</option>${headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('')}</select></label><label>País<select id="mapCountry"><option value="">Automático</option>${headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('')}</select></label><label>Comisión<select id="mapCom"><option value="">Automático</option>${headers.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('')}</select></label></div><div class="im-table-wrap"><table class="im-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${first.map(r=>`<tr>${headers.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;document.querySelector('#imImport').disabled=false}
function value(r,explicit,keys){return explicit?String(r[explicit]??'').trim():String(findKey(r,keys)||'').trim()}
function countryInfo(v){const n=norm(v);for(const [code,[name]] of Object.entries(countries)){if(n===norm(code)||n===norm(name)||n.includes(norm(name))||n===norm(code))return {code,name}};return {code:'',name:v||'Sin país'}}
async function importEval(){const sb=window.supabase?.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);if(!sb)throw new Error('Supabase no disponible');const u=await sb.auth.getUser();if(!u.data.user)throw new Error('Sesión no disponible');const modal=document.querySelector('#r17ImportModal');const sel=modal.querySelector('#imCommission');const commissionId=sel?.value||null;let imported=0,skipped=0;for(const r of parsed){const name=value(r,modal.querySelector('#mapName')?.value,['nombrecompleto','nombre','participante','delegado','estudiante']);if(!name){skipped++;continue}const ci=countryInfo(value(r,modal.querySelector('#mapCountry')?.value,['pais','país','delegacion','delegación','country','nacion','nación']));let comId=commissionId;const cv=value(r,modal.querySelector('#mapCom')?.value,['comision','comisión','comite','comité','committee']);if(cv){const q=(currentEval?[]:[]);const existing=(window.__r17EvalCommissions||[]).find(c=>norm(c.nombre)===norm(cv));if(existing)comId=existing.id}let d=null;const q=await sb.from('evaluacion_delegaciones').select('*').eq('evaluacion_id',currentEval).eq('codigo_pais',ci.code).eq('comision_id',comId).maybeSingle();if(q.error)throw q.error;d=q.data;if(!d){const ins=await sb.from('evaluacion_delegaciones').insert({evaluacion_id:currentEval,comision_id:comId,pais:ci.name,nombre_oficial:ci.name,codigo_pais:ci.code||'XX',bandera_emoji:flag(ci.code)}).select().single();if(ins.error)throw ins.error;d=ins.data}const ins=await sb.from('evaluacion_participantes').insert({evaluacion_id:currentEval,comision_id:comId,delegacion_id:d.id,nombre,delegacion:ci.name,identificador:`IMP-${Date.now().toString(36)}-${imported+1}`});if(ins.error){skipped++;continue}imported++}return{imported,skipped}}
async function importAcc(){const sb=window.supabase?.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);if(!sb)throw new Error('Supabase no disponible');const u=await sb.auth.getUser();if(!u.data.user)throw new Error('Sesión no disponible');let imported=0,skipped=0;for(const r of parsed){const full=value(r,document.querySelector('#mapName')?.value,['nombre','nombrecompleto','nombre completo','delegado']);const ap=value(r,'',['apellido','apellidos']);const parts=full.split(/\s+/);const nombre=full&&!ap?parts.shift()||full:full;const apellido=ap||parts.join(' ')||'N/A';if(!full){skipped++;continue}const tel=value(r,'',['telefono','teléfono','phone','celular']);const centro=value(r,'',['centroeducativo','centro educativo','centro','colegio','institucion','institución'])||'No especificado';const distrito=value(r,'',['distrito','distritoeducativo','distrito educativo']);const etapa=value(r,'',['etapa'])||'Distrital';const area=value(r,'',['area','área'])||'distrital';const ins=await sb.from('acreditacion_delegados').insert({codigo:`IMP-${Date.now().toString(36)}-${imported+1}`,nombre,apellido,telefono:tel||'N/A',cedula:value(r,'',['cedula','cédula']),acta_nacimiento:value(r,'',['acta','actadenacimiento','acta de nacimiento']),area,etapa,distrito_id:distrito||null,centro_educativo:centro,tutor_nombre:value(r,'',['tutor','familiar','familiar/tutor'])||'N/A',tutor_telefono:value(r,'',['telefonotutor','teléfonotutor','teléfono familiar'])||'N/A',presenta_alergia:/^(si|sí|yes|true|1)$/i.test(value(r,'',['alergia','presentaalergia','presenta alergia'])),alergia_detalle:value(r,'',['detallealergia','especificaciondealergia','especificación de alergia']),estado:'Pendiente',created_by:u.data.user.id});if(ins.error){skipped++;continue}imported++}return{imported,skipped}}
async function doImport(){const b=document.querySelector('#imImport'),status=document.querySelector('#imStatus');b.disabled=true;b.textContent='Importando…';try{const r=target==='evaluacion'?await importEval():await importAcc();status.textContent=`Importación completada: ${r.imported} registros agregados${r.skipped?` · ${r.skipped} omitidos`:''}.`;b.textContent='Completado';setTimeout(()=>{close();location.reload()},700)}catch(e){status.textContent='Error: '+e.message;b.disabled=false;b.textContent='Reintentar'}}
function injectEval(){const modal=document.querySelector('.r17ea-modal');if(!modal||document.getElementById('r17ImportEvalBtn'))return;const btn=document.createElement('button');btn.id='r17ImportEvalBtn';btn.id='r17ImportEvalBtn';btn.className='r17ea-tab';btn.textContent='📥 Importar masivo';const tabs=modal.querySelector('.r17ea-tabs');if(tabs){tabs.appendChild(btn);btn.onclick=()=>{currentEval=window.__r17CurrentEvaluationId||document.querySelector('.r17ea-overlay')?.dataset?.evaluationId||null;const s=window.__r17EvalState||{};currentEval=currentEval||s.current?.id;window.__r17EvalCommissions=s.commissions||[];open('evaluacion');setTimeout(()=>{const o=document.querySelector('#imOptions');o.innerHTML=`<label style="display:block;font-size:10px;font-weight:800;color:#53677d">Comisión destino<select id="imCommission" style="width:100%;margin-top:5px;padding:9px;border:1px solid #d5e0ea;border-radius:8px"><option value="">Sin comisión / usar la del archivo</option>${window.__r17EvalCommissions.map(c=>`<option value="${c.id}">${esc(c.nombre)}</option>`).join('')}</select></label>`},0)}}}
function injectAcc(){if(!document.querySelector('#acr2-list'))return;if(document.getElementById('r17ImportAccBtn'))return;const ref=document.querySelector('#acr2-x')?.parentElement;if(!ref)return;const b=document.createElement('button');b.id='r17ImportAccBtn';b.type='button';b.textContent='📥 Importar masivo';b.className='acr2-btn';ref.appendChild(b);b.onclick=()=>open('acreditacion')}
const obs=new MutationObserver(()=>{injectEval();injectAcc()});obs.observe(document.body,{childList:true,subtree:true});
setInterval(()=>{injectEval();injectAcc()},1500);
window.addEventListener('r17:eval-state',e=>{window.__r17EvalState=e.detail||{}});
document.addEventListener('click',e=>{if(e.target.closest('#imImport'))doImport()},true);
})();
