/* Regional 17 Volunteers — Biblioteca funcional local-first
   Persistencia: localStorage para metadatos + IndexedDB para archivos.
   Diseñada para sustituir posteriormente el adapter por Supabase Storage/Database. */
(() => {
'use strict';
const STORE='r17_library_v2', DB='r17_library_files_v2', BUCKET='files';
const MANAGERS=['admin','coordinador','comunicacion'];
let session=null,profile=null,state={folders:[],files:[],links:[]},current=null,root=null,search='',db=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const now=()=>new Date().toISOString();
const canManage=()=>MANAGERS.includes(profile?.role);
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
const toast=(m,e=false)=>{const x=document.createElement('div');x.className='toast'+(e?' error':'');x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),3200)};
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x&&Array.isArray(x.folders)&&Array.isArray(x.files)&&Array.isArray(x.links))state=x}catch{}}
function openDB(){return new Promise((resolve,reject)=>{if(db)return resolve(db);const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(BUCKET))r.result.createObjectStore(BUCKET)};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function putBlob(id,blob){return openDB().then(d=>new Promise((res,rej)=>{const t=d.transaction(BUCKET,'readwrite');t.objectStore(BUCKET).put(blob,id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)}))}
function getBlob(id){return openDB().then(d=>new Promise((res,rej)=>{const t=d.transaction(BUCKET,'readonly'),r=t.objectStore(BUCKET).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}))}
function delBlob(id){return openDB().then(d=>new Promise((res,rej)=>{const t=d.transaction(BUCKET,'readwrite');t.objectStore(BUCKET).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)}))}
function descendants(folderId){const ids=new Set([folderId]);let changed=true;while(changed){changed=false;state.folders.forEach(f=>{if(f.parentId&&ids.has(f.parentId)&&!ids.has(f.id)){ids.add(f.id);changed=true}})}return ids}
function folderName(id){return id?state.folders.find(f=>f.id===id)?.name||'Carpeta':'Biblioteca'}
function pathFor(id){const out=[];let f=state.folders.find(x=>x.id===id);while(f){out.unshift(f);f=state.folders.find(x=>x.id===f.parentId)}return out}
function siblingsDuplicate(name,parentId,ignore){return state.folders.some(f=>f.parentId===(parentId||null)&&f.id!==ignore&&f.name.trim().toLowerCase()===name.trim().toLowerCase())}
function linkUrl(raw){let u;try{u=new URL(raw.trim());if(u.protocol!=='https:')return null;return u.toString()}catch{return null}}
function youtubeId(raw){try{const u=new URL(raw);if(u.hostname==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||null;if(/youtube\.com$/i.test(u.hostname)||/youtube-nocookie\.com$/i.test(u.hostname)){if(u.pathname==='/watch')return u.searchParams.get('v');const p=u.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]))return p[1]||null}}catch{}return null}
function thumb(url){const id=youtubeId(url);return id?`https://img.youtube.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:''}
function init(){loadState();try{window.supabase?.createClient(window.RV_CONFIG.SUPABASE_URL,window.RV_CONFIG.SUPABASE_ANON_KEY).auth.getSession().then(async r=>{session=r.data?.session||null;if(session){const c=window.supabase.createClient(window.RV_CONFIG.SUPABASE_URL,window.RV_CONFIG.SUPABASE_ANON_KEY);const p=await c.from('profiles').select('role,full_name,email').eq('id',session.user.id).maybeSingle();profile=p.data||{role:'voluntario'}}install()})}catch{}install()}
function install(){const nav=document.querySelector('.sidebar nav');if(!nav||nav.querySelector('[data-r17-library]'))return;const b=document.createElement('button');b.className='nav-item';b.dataset.r17Library='1';b.innerHTML='<span>📚</span>Biblioteca';b.onclick=e=>{e.preventDefault();open()};nav.appendChild(b)}
function visible(){const f=current;let folders=state.folders.filter(x=>(x.parentId||null)===(f||null)),files=state.files.filter(x=>(x.folderId||null)===(f||null)),links=state.links.filter(x=>(x.folderId||null)===(f||null));if(search.trim()){const q=search.toLowerCase();const match=s=>s.toLowerCase().includes(q);folders=state.folders.filter(x=>match(x.name)||pathFor(x.parentId).some(p=>match(p.name)));files=state.files.filter(x=>match(x.name)||match(x.type)||pathFor(x.folderId).some(p=>match(p.name)));links=state.links.filter(x=>match(x.title)||match(x.description)||match(x.url)||pathFor(x.folderId).some(p=>match(p.name)))}return{folders,files,links}}
function header(){const crumbs=pathFor(current);return `<div class="library-count" style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><button class="btn small" data-root>Biblioteca</button>${crumbs.map((f,i)=>`<span>›</span><button class="btn small" data-bread="${f.id}">${esc(f.name)}</button>`).join('')}</div>`}
function render(){if(!root)return;const v=visible();root.querySelector('#libCrumbs').innerHTML=header();root.querySelector('#libCount').textContent=`${v.folders.length+v.files.length+v.links.length} elemento${v.folders.length+v.files.length+v.links.length===1?'':'s'}`;root.querySelector('#libGrid').innerHTML=[...v.folders.map(f=>`<article class="activity-card library-card"><div class="library-icon">📁</div><div class="grow"><h3>${esc(f.name)}</h3><p>Carpeta · ${state.folders.filter(x=>x.parentId===f.id).length} subcarpetas</p><div class="card-actions"><button class="btn small primary" data-open-folder="${f.id}">Abrir</button>${canManage()?`<button class="btn small" data-edit-folder="${f.id}">Editar</button><button class="btn small danger" data-delete-folder="${f.id}">Eliminar</button>`:''}</div></div></article>`),...v.files.map(f=>`<article class="activity-card library-card"><div class="library-icon">${fileIcon(f.type,f.name)}</div><div class="grow"><h3>${esc(f.name)}</h3><p>Archivo · ${esc(f.type||'Archivo')} · ${fmtSize(f.size)} · ${fmtDate(f.createdAt)}</p><div class="card-actions"><button class="btn small primary" data-open-file="${f.id}">Abrir</button><button class="btn small" data-download-file="${f.id}">Descargar</button>${canManage()?`<button class="btn small danger" data-delete-file="${f.id}">Eliminar</button>`:''}</div></div></article>`),...v.links.map(l=>`<article class="activity-card library-card"><div class="library-icon">${l.youtubeId?'▶️':'🔗'}</div><div class="grow"><h3>${esc(l.title)}</h3><p>Enlace · ${esc(l.description||l.url)}</p>${l.thumbnail?`<img src="${esc(l.thumbnail)}" alt="" style="max-width:160px;border-radius:8px;margin:6px 0">`:''}<div class="card-actions"><button class="btn small primary" data-open-link="${l.id}">Abrir</button>${canManage()?`<button class="btn small" data-edit-link="${l.id}">Editar</button><button class="btn small danger" data-delete-link="${l.id}">Eliminar</button>`:''}</div></div></article>`)].join('')||`<div class="empty" style="grid-column:1/-1"><div class="empty-icon">📚</div><h3>${search?'No se encontraron resultados':'Esta carpeta está vacía'}</h3><p>${search?'Prueba otro término de búsqueda.':'Crea una carpeta, sube un archivo o agrega un enlace.'}</p></div>`;bind()}
function fmtSize(n){n=Number(n||0);if(!n)return'—';const u=['B','KB','MB','GB'];let i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function fmtDate(x){try{return new Intl.DateTimeFormat('es-DO',{dateStyle:'medium'}).format(new Date(x))}catch{return'—'}}
function fileIcon(t,n){const x=(t||n.split('.').pop()).toLowerCase();if(x.includes('pdf'))return'📕';if(x.includes('word')||x.includes('doc'))return'📘';if(x.includes('sheet')||x.includes('xls')||x.includes('csv'))return'📗';if(x.includes('presentation')||x.includes('ppt'))return'📙';if(x.startsWith('image/'))return'🖼️';return'📄'}
function modal(title,body){const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><div><h3>${title}</h3></div><button class="icon-btn" data-close>×</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());return o}
function folderForm(id){const f=id&&state.folders.find(x=>x.id===id),o=modal(id?'Editar carpeta':'Nueva carpeta',`<form id="folderForm"><field><label>Nombre</label><input name="name" required maxlength="160" value="${esc(f?.name||'')}"></field><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();const name=e.target.name.value.trim(),parent=f?.parentId||current||null;if(!name)return;if(siblingsDuplicate(name,parent,id))return toast('Ya existe una carpeta con ese nombre aquí',true);if(f){f.name=name;f.updatedAt=now()}else state.folders.push({id:uid(),name,parentId:current||null,createdAt:now(),updatedAt:now()});save();o.remove();render();toast(f?'Carpeta actualizada':'Carpeta creada')}}
function deleteFolder(id){if(!confirm('¿Eliminar esta carpeta y TODO su contenido? Esta acción no se puede deshacer.'))return;const ids=descendants(id);const files=state.files.filter(f=>ids.has(f.folderId));Promise.all(files.map(f=>delBlob(f.id).catch(()=>{}))).then(()=>{state.folders=state.folders.filter(f=>!ids.has(f.id));state.files=state.files.filter(f=>!ids.has(f.folderId));state.links=state.links.filter(l=>!ids.has(l.folderId));if(ids.has(current))current=null;save();render();toast('Carpeta y contenido eliminados')})}
function fileUpload(){const o=modal('Subir archivo',`<form id="fileForm"><field><label>Archivo</label><input name="file" type="file" required></field><p>Se guardará dentro de: <b>${esc(folderName(current))}</b></p><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Subir archivo</button></div></form>`);o.querySelector('form').onsubmit=async e=>{e.preventDefault();const file=e.target.file.files[0];if(!file)return;const b=e.submitter;b.disabled=true;b.textContent='Subiendo…';try{const id=uid();await putBlob(id,file);state.files.push({id,name:file.name,size:file.size,type:file.type,folderId:current||null,createdAt:now(),updatedAt:now()});save();o.remove();render();toast('Archivo subido correctamente')}catch(err){toast('No se pudo guardar el archivo',true);b.disabled=false;b.textContent='Subir archivo'}}}
async function openFile(id){const f=state.files.find(x=>x.id===id);if(!f)return;const blob=await getBlob(id);if(!blob)return toast('Archivo no disponible',true);const u=URL.createObjectURL(blob);window.open(u,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function downloadFile(id){const f=state.files.find(x=>x.id===id),blob=await getBlob(id);if(!f||!blob)return toast('Archivo no disponible',true);const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
function deleteFile(id){if(!confirm('¿Eliminar este archivo?'))return;delBlob(id).finally(()=>{state.files=state.files.filter(f=>f.id!==id);save();render();toast('Archivo eliminado')})}
function linkForm(id){const l=id&&state.links.find(x=>x.id===id),o=modal(id?'Editar enlace':'Agregar enlace',`<form id="linkForm"><field><label>Título</label><input name="title" required maxlength="180" value="${esc(l?.title||'')}"></field><field><label>URL HTTPS</label><input name="url" type="url" required placeholder="https://…" value="${esc(l?.url||'')}"></field><field><label>Descripción</label><textarea name="description" maxlength="1000">${esc(l?.description||'')}</textarea></field><field><label>Miniatura opcional</label><input name="thumbnail" type="url" placeholder="https://…" value="${esc(l?.thumbnail||'')}"></field><p>Para YouTube se detectará automáticamente la miniatura.</p><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar</button></div></form>`);o.querySelector('form').onsubmit=e=>{e.preventDefault();const url=linkUrl(e.target.url.value);if(!url)return toast('La URL debe ser HTTPS válida',true);const yt=youtubeId(url),data={title:e.target.title.value.trim(),url,description:e.target.description.value.trim(),thumbnail:e.target.thumbnail.value.trim()||thumb(url),youtubeId:yt||null,folderId:current||null,updatedAt:now()};if(!data.title)return toast('Escribe un título',true);if(l)Object.assign(l,data);else state.links.push({id:uid(),...data,createdAt:now()});save();o.remove();render();toast(l?'Enlace actualizado':'Enlace agregado')}}
function deleteLink(id){if(!confirm('¿Eliminar este enlace?'))return;state.links=state.links.filter(l=>l.id!==id);save();render();toast('Enlace eliminado')}
function bind(){if(!root)return;root.querySelectorAll('[data-open-folder]').forEach(b=>b.onclick=()=>{current=b.dataset.openFolder;search='';root.querySelector('#libSearch').value='';render()});root.querySelectorAll('[data-edit-folder]').forEach(b=>b.onclick=()=>folderForm(b.dataset.editFolder));root.querySelectorAll('[data-delete-folder]').forEach(b=>b.onclick=()=>deleteFolder(b.dataset.deleteFolder));root.querySelectorAll('[data-open-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.openFile));root.querySelectorAll('[data-download-file]').forEach(b=>b.onclick=()=>downloadFile(b.dataset.downloadFile));root.querySelectorAll('[data-delete-file]').forEach(b=>b.onclick=()=>deleteFile(b.dataset.deleteFile));root.querySelectorAll('[data-open-link]').forEach(b=>b.onclick=()=>{const l=state.links.find(x=>x.id===b.dataset.openLink);if(l)window.open(l.url,'_blank','noopener,noreferrer')});root.querySelectorAll('[data-edit-link]').forEach(b=>b.onclick=()=>linkForm(b.dataset.editLink));root.querySelectorAll('[data-delete-link]').forEach(b=>b.onclick=()=>deleteLink(b.dataset.deleteLink));root.querySelectorAll('[data-bread]').forEach(b=>b.onclick=()=>{current=b.dataset.bread;render()});root.querySelector('[data-root]')?.addEventListener('click',()=>{current=null;render()})}
function open(){loadState();current=null;search='';root=document.createElement('div');root.className='overlay';root.innerHTML=`<div class="modal library-modal"><div class="modal-head"><div><h3>Biblioteca</h3><p>Archivos, carpetas y enlaces</p></div><button class="icon-btn" data-close>×</button></div><div class="modal-body"><div id="libCrumbs"></div><div class="toolbar"><div class="search"><span>⌕</span><input id="libSearch" placeholder="Buscar en toda la biblioteca…"></div>${canManage()?'<button class="btn" id="newFolder">＋ Carpeta</button><button class="btn" id="uploadFile">↑ Archivo</button><button class="btn primary" id="newLink">🔗 Agregar enlace</button>':''}</div><div class="library-count" id="libCount"></div><div id="libGrid" class="cards-grid library-grid"></div></div></div>`;document.body.appendChild(root);root.querySelector('[data-close]').onclick=()=>{root.remove();root=null};root.querySelector('#libSearch').oninput=e=>{search=e.target.value;render()};root.querySelector('#newFolder')?.addEventListener('click',()=>folderForm());root.querySelector('#uploadFile')?.addEventListener('click',fileUpload);root.querySelector('#newLink')?.addEventListener('click',()=>linkForm());render()}
window.R17Library={open,refresh:render};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
new MutationObserver(install).observe(document.body,{childList:true,subtree:true});
})();
