/* Perfil interactivo del usuario — Supabase Storage */
(() => {
  'use strict';
  const BUCKET='profile-avatars';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  let bound=false;
  function client(){return window.supabaseClient||window.sb||window._supabase||null}
  function currentUserId(){return window.__RV_SESSION?.user?.id||window.session?.user?.id||window.currentUser?.id||null}
  function userInfo(){const el=document.querySelector('.user-mini');return {name:el?.querySelector('strong')?.textContent||'Usuario',role:el?.querySelector('small')?.textContent||'Voluntario'}}
  function initials(name){return (name||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
  async function getAvatar(){const sb=client(),uid=currentUserId();if(!sb||!uid)return '';const {data}=sb.storage.from(BUCKET).getPublicUrl(`${uid}/avatar.jpg`);return data?.publicUrl||''}
  async function applyAvatar(){const src=await getAvatar();document.querySelectorAll('.user-mini .avatar').forEach(a=>{if(src){if(a.querySelector('img')?.src?.startsWith(src))return;a.innerHTML=`<img src="${src}?v=${Date.now()}" alt="Foto de perfil">`;a.classList.add('has-photo')}else{a.textContent=initials(userInfo().name);a.classList.remove('has-photo')}})}
  async function profile(){const {name:user,role}=userInfo(),photo=await getAvatar(),content=document.getElementById('content');if(!content)return;content.innerHTML=`<div class="profile-page"><div class="profile-cover"><div class="profile-avatar-wrap"><div class="profile-avatar ${photo?'has-photo':''}" id="profileAvatar">${photo?`<img src="${photo}?v=${Date.now()}" alt="Foto de perfil">`:initials(user)}</div><label class="profile-photo-btn" title="Cambiar foto"><input id="profilePhoto" type="file" accept="image/png,image/jpeg,image/webp">📷 Cambiar foto</label></div><div class="profile-identity"><span>MI PERFIL</span><h2>${esc(user)}</h2><p>${esc(role)}</p></div></div><div class="profile-grid"><section class="profile-card"><div class="profile-card-head"><div><h3>Información de la cuenta</h3><p>Datos de tu sesión actual</p></div></div><div class="profile-info"><div><small>Nombre</small><b>${esc(user)}</b></div><div><small>Rol</small><b>${esc(role)}</b></div></div></section><section class="profile-card"><div class="profile-card-head"><div><h3>Foto de perfil</h3><p>Se guarda en tu cuenta.</p></div></div><div class="profile-photo-actions"><label class="btn primary"><input id="profilePhoto2" type="file" accept="image/png,image/jpeg,image/webp">Seleccionar imagen</label><button class="btn" id="removeProfilePhoto" ${photo?'':'disabled'}>Eliminar foto</button></div><small class="profile-note">JPG, PNG o WEBP · Máximo 4 MB.</small></section></div></div>`;content.querySelectorAll('#profilePhoto,#profilePhoto2').forEach(input=>input.onchange=e=>savePhoto(e.target.files?.[0]));content.querySelector('#removeProfilePhoto')?.addEventListener('click',removePhoto)}
  async function savePhoto(file){const sb=client(),uid=currentUserId();if(!file||!sb||!uid){if(!sb||!uid)alert('No se encontró la sesión del usuario.');return}if(file.size>4*1024*1024){alert('La imagen debe pesar menos de 4 MB.');return}const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=async()=>{const max=500,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(async blob=>{if(!blob)return;const {error}=await sb.storage.from(BUCKET).upload(`${uid}/avatar.jpg`,blob,{contentType:'image/jpeg',upsert:true,cacheControl:'3600'});if(error){console.error(error);alert(`No se pudo guardar la foto: ${error.message||'error de Storage'}`);return}await applyAvatar();await profile()},'image/jpeg',.82)};img.onerror=()=>alert('No se pudo leer la imagen.');img.src=r.result};r.readAsDataURL(file)}
  async function removePhoto(){const sb=client(),uid=currentUserId();if(!sb||!uid)return;const {error}=await sb.storage.from(BUCKET).remove([`${uid}/avatar.jpg`]);if(error){alert(`No se pudo eliminar la foto: ${error.message||'error de Storage'}`);return}await applyAvatar();await profile()}
  function bind(){const el=document.querySelector('.user-mini');if(!el||bound)return;bound=true;el.style.cursor='pointer';el.title='Abrir mi perfil';el.addEventListener('click',profile);applyAvatar()}
  function start(){bind();if(!bound)setTimeout(start,500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
