-- ============================================================
-- seed.sql — Migración de datos existentes del registro
-- Regional 17 (Monte Plata) al esquema de Supabase/PostgreSQL
-- Ejecutar DESPUÉS de schema.sql, una sola vez.
-- ============================================================

begin;

-- Distritos
insert into public.distritos (id, nombre, regional) values
  ('17-01', 'Yamasá', 'Regional 17 Monte Plata'),
  ('17-02', 'Monte Plata', 'Regional 17 Monte Plata'),
  ('17-03', 'Bayaguana', 'Regional 17 Monte Plata'),
  ('17-04', 'Sabana Grande de Boyá', 'Regional 17 Monte Plata'),
  ('17-05', 'Esperalvillo', 'Regional 17 Monte Plata')
on conflict (id) do nothing;

-- Centros educativos (nivel secundario) precargados
insert into public.centros_educativos (distrito_id, nombre, nivel) values
  ('17-01', 'Politécnico Virginia Fidelina Matos de la Cruz', 'Secundario'),
  ('17-01', 'Politécnico General Eusebio Manzueta', 'Secundario'),
  ('17-01', 'Politécnico Parroquial Sor Susana Daly', 'Secundario'),
  ('17-01', 'Politécnico José de la Luz Guillén', 'Secundario'),
  ('17-02', 'Liceo Prof. Francis Matías', 'Secundario'),
  ('17-02', 'Liceo Gregorio Luperón (Don Juan)', 'Secundario'),
  ('17-02', 'Liceo Prof. Rogelio Guzmán', 'Secundario'),
  ('17-02', 'Liceo Académico El Cacique', 'Secundario'),
  ('17-02', 'Liceo Madre Ascención Nicol', 'Secundario'),
  ('17-02', 'Liceo Soriano Guzmán', 'Secundario'),
  ('17-02', 'Liceo Asia Luisa Concepción de Jesús', 'Secundario'),
  ('17-02', 'Politécnico José Francisco Peña Gómez', 'Secundario'),
  ('17-02', 'Politécnico Julio Abreu Cuello', 'Secundario'),
  ('17-02', 'Politécnico PROMAPEC', 'Secundario'),
  ('17-02', 'Liceo Mata Limón', 'Secundario'),
  ('17-02', 'Politécnico Ciudad del Conocimiento', 'Secundario'),
  ('17-03', 'Liceo José Pantaleón Castillo', 'Secundario'),
  ('17-03', 'Politécnico Morayma Veloz de Báez', 'Secundario'),
  ('17-03', 'Centro Educativo en Artes Prof. Félix Rafael Nova', 'Secundario'),
  ('17-03', 'Liceo María Eugenio de Hostos', 'Secundario'),
  ('17-04', 'Liceo Presbítero Carlos Nouel', 'Secundario'),
  ('17-04', 'Politécnico Gregorio Aybar Contreras', 'Secundario'),
  ('17-04', 'Politécnico Lic. Yolanda Esther Rivera', 'Secundario'),
  ('17-05', 'Politécnico Rafael Castillo Reinoso', 'Secundario'),
  ('17-05', 'Liceo Raúl Matos', 'Secundario')
on conflict (distrito_id, nombre) do nothing;

-- Voluntarios (roster inicial). Todos parten en estatus 'Sin contactar'
-- salvo que ya tuvieran otro estatus asignado en el registro anterior (no aplica aquí).
insert into public.voluntarios (nombre, distrito_id, categoria, estatus) values
  ('Adriana Nicol De Paula Morel', '17-01', 'Regional', 'Sin contactar'),
  ('Angélica Chery', '17-01', 'Distrital', 'Sin contactar'),
  ('Anyelina Mena Hernández', '17-01', 'Regional', 'Sin contactar'),
  ('Arianny Soto Franco', '17-01', 'Regional', 'Sin contactar'),
  ('Asley Dannery Doñé Rodríguez', '17-01', 'Regional', 'Sin contactar'),
  ('Cristalin De la Cruz Paulino', '17-01', 'Regional', 'Sin contactar'),
  ('Daniela Batista Muñoz', '17-01', 'Nacional', 'Sin contactar'),
  ('Elizabeth Ramirez', '17-01', 'Regional', 'Sin contactar'),
  ('Erica Jasmín Hernández Manzueta', '17-01', 'Distrital', 'Sin contactar'),
  ('Franchesca Genao Moya', '17-01', 'Regional', 'Sin contactar'),
  ('Freymel Emmanuel Rodríguez Mejia', '17-01', 'Regional', 'Sin contactar'),
  ('Hanna Crisllenny De Paula Moreno', '17-01', 'Regional', 'Sin contactar'),
  ('Helen Shalom De La Rosa De La Cruz', '17-01', 'Distrital', 'Sin contactar'),
  ('Isauri Suárez Severino', '17-01', 'Distrital', 'Sin contactar'),
  ('Jazmin Elvira Norel Manzueta', '17-01', 'Nacional', 'Sin contactar'),
  ('Jean Carlos Castro Gómez', '17-01', 'Regional', 'Sin contactar'),
  ('Jederlin Javier Martínez', '17-01', 'Regional', 'Sin contactar'),
  ('Jefferson Steven Paulino Borge', '17-01', 'Regional', 'Sin contactar'),
  ('Luis Alfredo Severino', '17-01', 'Regional', 'Sin contactar'),
  ('Mariel Abigail Abad Morillo', '17-01', 'Regional', 'Sin contactar'),
  ('Melani Mendoza Martinez', '17-01', 'Distrital', 'Sin contactar'),
  ('Nathalia Carolina Dotel Ortega', '17-01', 'Distrital', 'Sin contactar'),
  ('Noe Mancebo Quezada', '17-01', 'Distrital', 'Sin contactar'),
  ('Richarson Alejandro De Paula Abreu', '17-01', 'Regional', 'Sin contactar'),
  ('Rochely Mayreni De León Moreno', '17-01', 'Distrital', 'Sin contactar'),
  ('Rudy Deivy Agüero Quezada', '17-01', 'Distrital', 'Sin contactar'),
  ('Sefora Esther Mojica Meléndez', '17-01', 'Regional', 'Sin contactar'),
  ('Waida Fransel García Ferreras', '17-01', 'Regional', 'Sin contactar'),
  ('Yanelitza Nicole Hiciano Martínez', '17-01', 'Distrital', 'Sin contactar'),
  ('Yokeiry De La Cruz De León', '17-01', 'Regional', 'Sin contactar'),
  ('Yorky María Henriquez', '17-01', 'Regional', 'Sin contactar'),
  ('Almysbel Rodríguez Ovalle', '17-02', 'Regional', 'Sin contactar'),
  ('Arlen Alainy Morillo Rodríguez', '17-02', 'Regional', 'Sin contactar'),
  ('Brenda Iveth De León Vargas', '17-02', 'Nacional', 'Sin contactar'),
  ('Carlos Alfredo Mejía Pimentel', '17-02', 'Nacional', 'Sin contactar'),
  ('Dana Del Rosario Jorge', '17-02', 'Distrital', 'Sin contactar'),
  ('Daribel Laureano Nolasco', '17-02', 'Regional', 'Sin contactar'),
  ('Edgar Alejandro Reyes Fanith', '17-02', 'Regional', 'Sin contactar'),
  ('Emilia Leocadio Ramirez', '17-02', 'Distrital', 'Sin contactar'),
  ('Heidy Díaz De los Santos', '17-02', 'Regional', 'Sin contactar'),
  ('Iandra Carolina Valera Caraballo', '17-02', 'Regional', 'Sin contactar'),
  ('Irialny Fabián Rojas', '17-02', 'Regional', 'Sin contactar'),
  ('Irma Catano de León', '17-02', 'Regional', 'Sin contactar'),
  ('Isaira Cuello Sebastián', '17-02', 'Nacional', 'Sin contactar'),
  ('Ismailyn Waleska Estévez Castro', '17-02', 'Distrital', 'Sin contactar'),
  ('Jogenny Mercedes Zorrilla Ovalle', '17-02', 'Regional', 'Sin contactar'),
  ('Juan Daniel Mateo', '17-02', 'Distrital', 'Sin contactar'),
  ('Mairelis Travieso del Rosario', '17-02', 'Regional', 'Sin contactar'),
  ('Mairenis Travieso del Rosario', '17-02', 'Nacional', 'Sin contactar'),
  ('Michael Antonio Polanco', '17-02', 'Regional', 'Sin contactar'),
  ('Osnairelin Osbirna Bello Marte', '17-02', 'Distrital', 'Sin contactar'),
  ('Osneilyn Manzanillo Guzman', '17-02', 'Regional', 'Sin contactar'),
  ('Rosmery Alexandra Gómez Vegazo', '17-02', 'Distrital', 'Sin contactar'),
  ('Shania Martinez', '17-02', 'Regional', 'Sin contactar'),
  ('Christopher Noah Ureña Molina', '17-03', 'Distrital', 'Sin contactar'),
  ('Daneuri Manuel Ramírez Tolentino', '17-03', 'Distrital', 'Sin contactar'),
  ('Eddylainis Javier Leyba', '17-03', 'Regional', 'Sin contactar'),
  ('Eunice Nicole Consoró Brito', '17-03', 'Regional', 'Sin contactar'),
  ('Flabia Mariel Frias Hichez', '17-03', 'Regional', 'Sin contactar'),
  ('Francisco Alberto Santana Castillo', '17-03', 'Regional', 'Sin contactar'),
  ('Génesis Nicole Ortiz Heredia', '17-03', 'Distrital', 'Sin contactar'),
  ('Gisela Amboise', '17-03', 'Distrital', 'Sin contactar'),
  ('Melani Diosmery Del Carmen Castillo', '17-03', 'Regional', 'Sin contactar'),
  ('Rosio Esneida Sosa Jiménez', '17-03', 'Regional', 'Sin contactar'),
  ('Solianny Elizabeth Alcántara Padilla', '17-03', 'Regional', 'Sin contactar'),
  ('Victor Arismendy Díaz Mota', '17-03', 'Regional', 'Sin contactar'),
  ('Victor Jose Sosa Ortiz', '17-03', 'Regional', 'Sin contactar'),
  ('Vivianlys Batista Peguero', '17-03', 'Regional', 'Sin contactar'),
  ('Waderlin Lugo', '17-03', 'Distrital', 'Sin contactar'),
  ('Wenchida Occenat', '17-03', 'Distrital', 'Sin contactar'),
  ('Albert Jesús Silvestre Javier', '17-04', 'Regional', 'Sin contactar'),
  ('Ana Milagros Romero de los Santos', '17-04', 'Regional', 'Sin contactar'),
  ('Carlos Fabian Jean Bautista', '17-04', 'Distrital', 'Sin contactar'),
  ('Darbelis Esmeralda Vilchez Contreras', '17-04', 'Regional', 'Sin contactar'),
  ('Digna Maria de Leon Rosario', '17-04', 'Regional', 'Sin contactar'),
  ('Esmeralda Elis Valdez', '17-04', 'Regional', 'Sin contactar'),
  ('Eugenis Raquel Mejia Benitez', '17-04', 'Nacional', 'Sin contactar'),
  ('Gelson López', '17-04', 'Regional', 'Sin contactar'),
  ('Jesús Daniel Nuñez Figueroa', '17-04', 'Regional', 'Sin contactar'),
  ('Jireth Buenaventura Martinez Santana', '17-04', 'Regional', 'Sin contactar'),
  ('Julia Lorena de Los Santos', '17-04', 'Distrital', 'Sin contactar'),
  ('Julian Laureano', '17-04', 'Regional', 'Sin contactar'),
  ('Mariela Chevalier Holguín', '17-04', 'Distrital', 'Sin contactar'),
  ('Marylania Jaquez Ramirez', '17-04', 'Distrital', 'Sin contactar'),
  ('Melani Solymar Mejia Rivas', '17-04', 'Regional', 'Sin contactar'),
  ('Slaidy Maria Rosario Disla', '17-04', 'Regional', 'Sin contactar'),
  ('Arbelis Peña Belén', '17-05', 'Regional', 'Sin contactar'),
  ('Carmen Nardelys Duarte Espinal', '17-05', 'Regional', 'Sin contactar'),
  ('Darianny Mueses Mueses', '17-05', 'Regional', 'Sin contactar'),
  ('Darwin Ariel Mateo Hernández', '17-05', 'Regional', 'Sin contactar'),
  ('Elisandra Tolentino Severino', '17-05', 'Regional', 'Sin contactar'),
  ('José Bautista De la Cruz Martínez', '17-05', 'Regional', 'Sin contactar'),
  ('Jose Gabriel Diaz Evangelista', '17-05', 'Regional', 'Sin contactar'),
  ('Jose Luis De la Cruz Fajardo', '17-05', 'Distrital', 'Sin contactar'),
  ('Marianny Valdez Baldez', '17-05', 'Distrital', 'Sin contactar'),
  ('Nicol Mariel Quezada Colón', '17-05', 'Regional', 'Sin contactar');

commit;