(() => {
  const wait=()=>{const b=document.getElementById('selection');if(!b)return setTimeout(wait,250);b.addEventListener('click',()=>setTimeout(openSelection,0));};
  async function openSelection(){
    const root=document.getElementById('content');
    const sup=window.supabase.createClient(window.RV_CONFIG.SUPABASE_URL,window.RV_CONFIG.SUPABASE_ANON_KEY);
    root.innerHTML=`<div class="selection-layout"><div class="panel"><div class="panel-head"><div><h3>Selección inteligente de voluntarios</h3><p>Prioriza desempeño y experiencia relacionada con el rol.</p></div></div><field><label>Actividad</label><select id="sx-act"><option value="">Cargando…</option></select></field><div class="form-grid"><field><label>Cantidad requerida</label><input id="sx-need" type="number" min="1" value="10"></field><field><label>Rol requerido</label><select id="sx-role"><option value="">Cualquier rol</option></select></field></div><div class="search"><span>⌕</span><input id="sx-q" placeholder="Buscar candidato…"></div><div id="sx-list" class="candidate-list">Cargando candidatos…</div><button id="sx-confirm" class="btn primary" disabled>Confirmar selección</button></div></div>`;
    const [a,r,v,p,perf]=await Promise.all([sup.from('actividades').select('*').eq('is_active',true).order('fecha',{ascending:false}),sup.from('roles_actividad').select('*').eq('activo',true).order('nombre'),sup.from('voluntarios').select('*'),sup.from('participaciones').select('*'),sup.from('voluntario_desempeno').select('*')]);
    if(a.error||r.error||v.error||p.error||perf.error){root.innerHTML='<div class="error-box">No se pudo cargar la selección de voluntarios.</div>';return}
    const activities=a.data||[],roles=r.data||[],volunteers=v.data||[],parts=p.data||[],performance=perf.data||[];let selected=new Set();
    const act=document.getElementById('sx-act'),role=document.getElementById('sx-role'),need=document.getElementById('sx-need'),search=document.getElementById('sx-q'),list=document.getElementById('sx-list'),confirm=document.getElementById('sx-confirm');
    act.innerHTML='<option value="">Selecciona una actividad</option>'+activities.map(x=>`<option value="${x.id}">${esc(x.nombre)} · ${x.fecha}</option>`).join('');role.innerHTML+='<option value="">Cualquier rol</option>'+roles.map(x=>`<option>${esc(x.nombre)}</option>`).join('');
    const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
    function draw(){const aid=act.value,rn=role.value,q=(search.value||'').toLowerCase(),already=new Set(parts.filter(x=>x.actividad_id===aid).map(x=>x.voluntario_id));let rows=volunteers.filter(x=>!already.has(x.id)&&(!q||x.nombre.toLowerCase().includes(q))).map(v=>{const ps=parts.filter(x=>x.voluntario_id===v.id),exp=ps.filter(x=>!rn||roles.find(r=>r.id===x.rol_id)?.nombre===rn).length,pr=performance.find(x=>x.voluntario_id===v.id)||{};return{v,exp,score:Number(pr.indice||0)}});rows.sort((x,y)=>(y.exp*10+y.score)-(x.exp*10+x.score));list.innerHTML=rows.length?rows.map(x=>`<label class="candidate ${selected.has(x.v.id)?'chosen':''}"><input type="checkbox" data-sx="${x.v.id}" ${selected.has(x.v.id)?'checked':''}><div class="avatar">${esc(x.v.nombre[0])}</div><div class="grow"><strong>${esc(x.v.nombre)}</strong><small>${esc(x.exp)} experiencias en ${esc(rn||'roles')} · desempeño ${x.score.toFixed(0)}</small></div><b>${x.score.toFixed(0)}</b></label>`).join(''):'<div class="empty">No hay candidatos disponibles para estos criterios.</div>';list.querySelectorAll('[data-sx]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.sx):selected.delete(c.dataset.sx);draw()});confirm.disabled=!aid||selected.size===0||selected.size>Number(need.value||10);confirm.textContent=`Confirmar selección (${selected.size}/${Number(need.value||10)})`}
    [act,role,need,search].forEach(x=>x.addEventListener('input',draw));act.addEventListener('change',draw);role.addEventListener('change',draw);draw();
    confirm.onclick=async()=>{const aid=act.value;if(!aid||!selected.size)return;confirm.disabled=true;const rows=[...selected].map(id=>({voluntario_id:id,actividad_id:aid,fecha:activities.find(x=>x.id===aid)?.fecha,horas_colaboradas:0,asistencia:false}));const {error}=await sup.from('participaciones').insert(rows);if(error){console.error(error);alert(error.code==='23505'?'Uno o más voluntarios ya están registrados en esta actividad.':'No se pudo confirmar la selección.');confirm.disabled=false;return}selected.clear();await openSelection();}
  }
  const old=window.addEventListener('load',wait);setTimeout(wait,500);
})();

// Load the master-administration module once the main app has initialized.
(()=>{const load=()=>{if(document.querySelector('script[data-r17-admin-loader]'))return;const s=document.createElement('script');s.src='admin.js?v=master-admin-1';s.dataset.r17AdminLoader='1';s.async=false;document.head.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();})();

// Load the calendar and visual schedule module after the main application.
(()=>{const load=()=>{if(document.querySelector('script[data-r17-calendar-loader]'))return;const s=document.createElement('script');s.src='calendar.js?v=1';s.dataset.r17CalendarLoader='1';s.async=false;document.head.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();})();

// Load the navigation stability patch after the calendar module.
(()=>{const load=()=>{if(document.querySelector('script[data-r17-calendar-fix-loader]'))return;const s=document.createElement('script');s.src='calendar-fix.js?v=1';s.dataset.r17CalendarFixLoader='1';s.async=false;document.head.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();})();