(() => {
  const wait=()=>{const b=document.getElementById('selection');if(!b)return setTimeout(wait,250);b.addEventListener('click',()=>setTimeout(openSelection,0));};
  async function openSelection(){
    const root=document.getElementById('content');
    const sup=window.supabase.createClient(window.RV_CONFIG.SUPABASE_URL,window.RV_CONFIG.SUPABASE_ANON_KEY);
    root.innerHTML=`<div class="selection-layout"><div class="panel"><div class="panel-head"><div><h3>Selección inteligente de voluntarios</h3><p>Prioriza desempeño y experiencia relacionada con el rol.</p></div></div><field><label>Actividad</label><select id="sx-act"><option value="">Cargando…</option></select></field><div class="form-grid"><field><label>Cantidad requerida</label><input id="sx-need" type="number" min="1" value="10"></field><field><label>Rol requerido</label><select id="sx-role"><option value="">Cualquier rol</option></select></field></div><div class="search"><span>⌕</span><input id="sx-q" placeholder="Buscar candidato…"></div><div id="sx-list" class="candidate-list">Cargando candidatos…</div><button id="sx-confirm" class="btn primary" disabled>Confirmar selección</button></div></div>`;
    const [a,r,v,p,perf]=await Promise.all([sup.from('actividades').select('*').eq('is_active',true).order('fecha',{ascending:false}),sup.from('roles_actividad').select('*').eq('activo',true).order('nombre'),sup.from('voluntarios').select('*'),sup.from('participaciones').select('*'),sup.from('voluntario_desempeno').select('*')]);
    if(a.error||r.error||v.error||p.error||perf.error){root.innerHTML='<div class="error-box">No se pudo cargar la selección de voluntarios.</div>';return}
    const activities=a.data||[],roles=r.data||[],volunteers=v.data||[],parts=p.data||[],performance=perf.data||[];let selected=new Set();
    const act=document.getElementById('sx-act'),role=document.getElementById('sx-role'),need=document.getElementById('sx-need'),search=document.getElementById('sx-q'),list=document.getElementById('sx-list'),confirm=document.getElementById('sx-confirm');
    const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
    act.innerHTML='<option value="">Selecciona una actividad</option>'+activities.map(x=>`<option value="${x.id}">${esc(x.nombre)} · ${x.fecha}</option>`).join('');role.innerHTML='<option value="">Cualquier rol</option>'+roles.map(x=>`<option value="${x.nombre}">${esc(x.nombre)}</option>`).join('');
    function draw(){const aid=act.value,rn=role.value,q=(search.value||'').toLowerCase(),already=new Set(parts.filter(x=>x.actividad_id===aid).map(x=>x.voluntario_id));let rows=volunteers.filter(x=>!already.has(x.id)&&(!q||x.nombre.toLowerCase().includes(q))).map(v=>{const ps=parts.filter(x=>x.voluntario_id===v.id),exp=ps.filter(x=>!rn||roles.find(r=>r.id===x.rol_id)?.nombre===rn).length,pr=performance.find(x=>x.voluntario_id===v.id)||{};return{v,exp,score:Number(pr.indice||0)}});rows.sort((x,y)=>(y.exp*10+y.score)-(x.exp*10+x.score));list.innerHTML=rows.length?rows.map(x=>`<label class="candidate ${selected.has(x.v.id)?'chosen':''}"><input type="checkbox" data-sx="${x.v.id}" ${selected.has(x.v.id)?'checked':''}><div class="avatar">${esc(x.v.nombre[0])}</div><div class="grow"><strong>${esc(x.v.nombre)}</strong><small>${esc(x.exp)} experiencias en ${esc(rn||'roles')} · desempeño ${x.score.toFixed(0)}</small></div><b>${x.score.toFixed(0)}</b></label>`).join(''):'<div class="empty">No hay candidatos disponibles para estos criterios.</div>';list.querySelectorAll('[data-sx]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.sx):selected.delete(c.dataset.sx);draw()});confirm.disabled=!aid||selected.size===0||selected.size>Number(need.value||10);confirm.textContent=`Confirmar selección (${selected.size}/${Number(need.value||10)})`}
    [act,role,need,search].forEach(x=>x.addEventListener('input',draw));act.addEventListener('change',draw);role.addEventListener('change',draw);
    draw();
    confirm.onclick=async()=>{const aid=act.value;if(!aid||!selected.size)return;confirm.disabled=true;const rows=[...selected].map(id=>({voluntario_id:id,actividad_id:aid,fecha:activities.find(x=>x.id===aid)?.fecha,horas_colaboradas:0,asistencia:false}));const {error}=await sup.from('participaciones').insert(rows);if(error){console.error(error);alert(error.code==='23505'?'Uno o más voluntarios ya están registrados en esta actividad.':'No se pudo confirmar la selección.');confirm.disabled=false;return}selected.clear();await openSelection();}
  }
  setTimeout(wait,500);
})();

/* Regional 17 — account registration, role administration, announcements and realtime chat */
(() => {
  'use strict';
  const cfg=window.RV_CONFIG||{};
  let client=null, channel=null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const toast=(m,type='success')=>{const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)};
  const getClient=()=>client||(client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY));
  const roleLabel=r=>({admin_maestro:'Administrador maestro',admin:'Administrador',coordinador:'Coordinador',comunicacion:'Comunicaciones',voluntario:'Voluntario'}[r]||r);
  async function registerModal(){
    const s=getClient(); const {data,error}=await s.rpc('available_volunteers');
    if(error){toast('No se pudieron cargar los voluntarios disponibles','error');return;}
    const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><div><h3>Crear cuenta de voluntario</h3><p style="margin:4px 0;color:#667085;font-size:11px">Selecciona tu nombre exactamente como aparece en Regional 17.</p></div><button class="icon-btn" data-close>×</button></div><div class="modal-body"><form id="rv-register"><field label="Nombre del voluntario"><select name="volunteer_id" required><option value="">Selecciona tu nombre</option>${(data||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.nombre)}</option>`).join('')}</select></field><field label="Correo electrónico"><input name="email" type="email" required autocomplete="email" placeholder="tu@correo.com"></field><field label="Contraseña"><input name="password" type="password" minlength="8" required autocomplete="new-password" placeholder="Mínimo 8 caracteres"></field><field label="Confirmar contraseña"><input name="confirm" type="password" minlength="8" required autocomplete="new-password"></field><p style="font-size:10px;color:#667085">Tu cuenta se vinculará al voluntario seleccionado y recibirá automáticamente el rol <b>Voluntario</b>. Si tu correo requiere confirmación, confirma el correo y vuelve a abrir la aplicación.</p><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary" id="rv-register-submit">Crear cuenta</button></div></form></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());
    o.querySelector('#rv-register').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),email=String(fd.get('email')).trim(),pw=String(fd.get('password')),confirm=String(fd.get('confirm')),vid=String(fd.get('volunteer_id'));if(pw!==confirm)return toast('Las contraseñas no coinciden','error');const b=e.submitter;b.disabled=true;b.textContent='Creando…';localStorage.setItem('rv_pending_volunteer',vid);const {data:auth,error:ae}=await s.auth.signUp({email,password:pw});if(ae){localStorage.removeItem('rv_pending_volunteer');b.disabled=false;b.textContent='Crear cuenta';toast(ae.message,'error');return}if(auth.session){const {error:ce}=await s.rpc('claim_volunteer_account',{target_volunteer_id:vid});if(ce){await s.auth.signOut();localStorage.removeItem('rv_pending_volunteer');b.disabled=false;b.textContent='Crear cuenta';toast(ce.message,'error');return}localStorage.removeItem('rv_pending_volunteer');o.remove();toast('Cuenta creada. Ya puedes entrar como Voluntario.');return}o.remove();toast('Cuenta creada. Revisa tu correo para confirmar la cuenta. Después podrás iniciar sesión.');};
  }
  function addRegisterButton(){const form=document.getElementById('login');if(!form||document.getElementById('rv-open-register'))return;const b=document.createElement('button');b.type='button';b.id='rv-open-register';b.className='btn full';b.style.marginTop='8px';b.textContent='Crear cuenta de voluntario';b.onclick=registerModal;form.after(b)}
  async function claimPending(){const vid=localStorage.getItem('rv_pending_volunteer');if(!vid)return;const s=getClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.rpc('claim_volunteer_account',{target_volunteer_id:vid});if(!error){localStorage.removeItem('rv_pending_volunteer');toast('Tu cuenta quedó vinculada al voluntario.')}else if(!/ya está vinculada|ya tiene una cuenta/i.test(error.message||''))console.warn(error)}
  function ensureNav(){const nav=document.querySelector('.sidebar nav');if(!nav)return;const r=window.__R17_PROFILE_ROLE||'';if(['admin_maestro'].includes(r)&&!document.getElementById('rv-users-nav')){const b=document.createElement('button');b.id='rv-users-nav';b.className='nav-item';b.innerHTML='<span>♙</span> Usuarios y roles';b.onclick=()=>showUsers();nav.appendChild(b)}if(!document.getElementById('rv-chat-nav')){const b=document.createElement('button');b.id='rv-chat-nav';b.className='nav-item';b.innerHTML='<span>💬</span> Chat';b.onclick=()=>showChat();nav.appendChild(b)}if(!document.getElementById('rv-ann-nav')){const b=document.createElement('button');b.id='rv-ann-nav';b.className='nav-item';b.innerHTML='<span>📢</span> Anuncios';b.onclick=()=>showAnnouncements();nav.appendChild(b)}}
  async function showUsers(){const s=getClient(),root=document.getElementById('content');root.innerHTML='<div class="panel"><h3>Usuarios y roles</h3><p>Cargando usuarios…</p></div>';const {data,error}=await s.rpc('admin_users_with_names');if(error){root.innerHTML=`<div class="error-box">${esc(error.message)}</div>`;return}root.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>👑 Usuarios y roles</h3><p>El administrador maestro puede asignar roles. El nombre se toma del voluntario vinculado.</p></div></div><div class="table-wrap"><table><thead><tr><th>Voluntario</th><th>Correo</th><th>Rol</th><th>Gestión</th></tr></thead><tbody>${(data||[]).map(u=>`<tr><td><div class="person"><div class="avatar">${esc((u.volunteer_name||u.full_name||u.email||'U')[0])}</div><div><strong>${esc(u.volunteer_name||u.full_name||'Sin nombre')}</strong><small>${u.volunteer_id?'Voluntario vinculado':'Sin vínculo'}</small></div></div></td><td>${esc(u.email||'—')}</td><td><span class="pill neutral">${esc(roleLabel(u.role))}</span></td><td>${u.role==='admin_maestro'?'<span class="pill success">Protegido</span>':`<select class="rv-role-select" data-user="${u.id}">${['voluntario','comunicacion','coordinador','admin'].map(r=>`<option value="${r}" ${u.role===r?'selected':''}>${roleLabel(r)}</option>`).join('')}</select>`}</td></tr>`).join('')||'<tr><td colspan="4">No hay usuarios.</td></tr>'}</tbody></table></div></div>`;root.querySelectorAll('.rv-role-select').forEach(sel=>sel.onchange=async()=>{sel.disabled=true;const {error}=await s.rpc('set_user_role',{target_user_id:sel.dataset.user,new_role:sel.value});sel.disabled=false;if(error){toast(error.message,'error');return}toast('Rol actualizado correctamente')})}
  async function showAnnouncements(){const s=getClient(),root=document.getElementById('content');const {data,error}=await s.from('announcements').select('*').order('created_at',{ascending:false});if(error){root.innerHTML=`<div class="error-box">${esc(error.message)}</div>`;return}const {data:{user}}=await s.auth.getUser();const {data:prof}=user?await s.from('profiles').select('role').eq('id',user.id).maybeSingle():{data:null};const can=['admin_maestro','admin','comunicacion'].includes(prof?.role);root.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>📢 Anuncios</h3><p>Comunicados oficiales para la comunidad Regional 17.</p></div>${can?'<button class="btn primary" id="rv-new-ann">＋ Nuevo anuncio</button>':''}</div><div id="rv-ann-list">${(data||[]).map(a=>`<article class="announcement"><div><span class="pill ${a.priority==='urgent'?'danger':'neutral'}">${esc(a.priority)}</span><h4>${esc(a.title)}</h4><p>${esc(a.content)}</p><small>${new Date(a.created_at).toLocaleString('es-DO')}</small></div>${can?`<button class="icon-action danger" data-ann-del="${a.id}">Eliminar</button>`:''}</article>`).join('')||'<div class="empty">No hay anuncios publicados.</div>'}</div></div>`;root.querySelector('#rv-new-ann')?.addEventListener('click',newAnnouncement);root.querySelectorAll('[data-ann-del]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este anuncio?'))return;b.disabled=true;const {error}=await s.from('announcements').delete().eq('id',b.dataset.annDel);if(error){b.disabled=false;toast(error.message,'error');return}toast('Anuncio eliminado');showAnnouncements()});if(channel)channel.unsubscribe();channel=s.channel('rv-announcements').on('postgres_changes',{event:'*',schema:'public',table:'announcements'},()=>showAnnouncements()).subscribe()}
  async function newAnnouncement(){const s=getClient();const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="modal"><div class="modal-head"><h3>Nuevo anuncio</h3><button class="icon-btn" data-close>×</button></div><div class="modal-body"><form id="rv-ann-form"><field label="Título del anuncio"><input name="title" required placeholder="Ej.: Reunión general de voluntarios"></field><field label="Contenido"><textarea name="content" required placeholder="Escribe aquí la información que deben conocer los voluntarios…"></textarea></field><field label="Prioridad"><select name="priority"><option value="normal">Normal</option><option value="important">Importante</option><option value="urgent">Urgente</option></select></field><div class="modal-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Publicar anuncio</button></div></form></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());o.querySelector('#rv-ann-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),{data:{user}}=await s.auth.getUser(),{error}=await s.from('announcements').insert({title:String(fd.get('title')).trim(),content:String(fd.get('content')).trim(),priority:fd.get('priority'),author_id:user?.id});if(error){toast(error.message,'error');return}o.remove();toast('Anuncio publicado');showAnnouncements()}}
  async function showChat(){const s=getClient(),root=document.getElementById('content');root.innerHTML=`<div class="panel"><div class="panel-head"><div><h3>💬 Chat Regional 17</h3><p>Comunicación general en tiempo real.</p></div></div><div id="rv-chat-box" style="height:55vh;overflow:auto;border:1px solid #e3e9f1;border-radius:12px;padding:12px">Cargando mensajes…</div><form id="rv-chat-form" style="display:flex;gap:8px;margin-top:10px"><input id="rv-chat-input" style="flex:1;border:1px solid #e3e9f1;border-radius:9px;padding:10px" maxlength="2000" required placeholder="Escribe un mensaje…"><button class="btn primary">Enviar</button></form></div>`;const box=root.querySelector('#rv-chat-box');const render=async()=>{const {data,error}=await s.from('chat_messages').select('id,user_id,message,created_at,profiles(full_name)').order('created_at',{ascending:true}).limit(200);if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(m=>`<div style="display:flex;gap:9px;padding:9px 0;border-bottom:1px solid #edf1f5"><div class="avatar">${esc((m.profiles?.full_name||'U')[0])}</div><div><strong>${esc(m.profiles?.full_name||'Usuario')}</strong><p style="margin:3px 0">${esc(m.message)}</p><small>${new Date(m.created_at).toLocaleString('es-DO')}</small></div></div>`).join('')||'<div class="empty">Todavía no hay mensajes.</div>';box.scrollTop=box.scrollHeight};await render();root.querySelector('#rv-chat-form').onsubmit=async e=>{e.preventDefault();const input=root.querySelector('#rv-chat-input'),msg=input.value.trim();if(!msg)return;const {data:{user}}=await s.auth.getUser();const {error}=await s.from('chat_messages').insert({user_id:user.id,message:msg});if(error){toast(error.message,'error');return}input.value='';await render()};if(channel)channel.unsubscribe();channel=s.channel('rv-chat-ui').on('postgres_changes',{event:'*',schema:'public',table:'chat_messages'},render).subscribe()}
  async function decorate(){addRegisterButton();claimPending();setInterval(()=>{if(document.getElementById('login'))addRegisterButton();else ensureNav()},400)}
  window.addEventListener('load',decorate);setTimeout(decorate,700);
})();